# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class AssemblyTranslate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'dx': 'float',
        'dy': 'float',
        'dz': 'float'
    }

    attribute_map = {
        'dx': 'dx',
        'dy': 'dy',
        'dz': 'dz'
    }

    def __init__(self, dx=None, dy=None, dz=None, local_vars_configuration=None):  # noqa: E501
        """AssemblyTranslate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._dx = None
        self._dy = None
        self._dz = None
        self.discriminator = None

        self.dx = dx
        self.dy = dy
        self.dz = dz

    @property
    def dx(self):
        """Gets the dx of this AssemblyTranslate.  # noqa: E501


        :return: The dx of this AssemblyTranslate.  # noqa: E501
        :rtype: float
        """
        return self._dx

    @dx.setter
    def dx(self, dx):
        """Sets the dx of this AssemblyTranslate.


        :param dx: The dx of this AssemblyTranslate.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and dx is None:  # noqa: E501
            raise ValueError("Invalid value for `dx`, must not be `None`")  # noqa: E501

        self._dx = dx

    @property
    def dy(self):
        """Gets the dy of this AssemblyTranslate.  # noqa: E501


        :return: The dy of this AssemblyTranslate.  # noqa: E501
        :rtype: float
        """
        return self._dy

    @dy.setter
    def dy(self, dy):
        """Sets the dy of this AssemblyTranslate.


        :param dy: The dy of this AssemblyTranslate.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and dy is None:  # noqa: E501
            raise ValueError("Invalid value for `dy`, must not be `None`")  # noqa: E501

        self._dy = dy

    @property
    def dz(self):
        """Gets the dz of this AssemblyTranslate.  # noqa: E501


        :return: The dz of this AssemblyTranslate.  # noqa: E501
        :rtype: float
        """
        return self._dz

    @dz.setter
    def dz(self, dz):
        """Sets the dz of this AssemblyTranslate.


        :param dz: The dz of this AssemblyTranslate.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and dz is None:  # noqa: E501
            raise ValueError("Invalid value for `dz`, must not be `None`")  # noqa: E501

        self._dz = dz

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssemblyTranslate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AssemblyTranslate):
            return True

        return self.to_dict() != other.to_dict()
