# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class Box(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'x': 'str',
        'x_calc': 'float',
        'y': 'str',
        'y_calc': 'float',
        'z': 'str',
        'z_calc': 'float',
        'dx': 'str',
        'dx_calc': 'float',
        'dy': 'str',
        'dy_calc': 'float',
        'dz': 'str',
        'dz_calc': 'float',
        'power': 'str',
        'power_calc': 'float',
        'sphere': 'bool',
        'material': 'int',
        'color': 'str',
        'material_name': 'str',
        'hc': 'str',
        'bound': 'bool',
        'hole': 'bool',
        'index': 'int',
        'type': 'str',
        'type_id': 'int',
        'leaf': 'bool',
        'parent': 'int',
        'visible': 'bool',
        'active': 'bool',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'x': 'x',
        'x_calc': 'x_calc',
        'y': 'y',
        'y_calc': 'y_calc',
        'z': 'z',
        'z_calc': 'z_calc',
        'dx': 'dx',
        'dx_calc': 'dx_calc',
        'dy': 'dy',
        'dy_calc': 'dy_calc',
        'dz': 'dz',
        'dz_calc': 'dz_calc',
        'power': 'power',
        'power_calc': 'power_calc',
        'sphere': 'sphere',
        'material': 'material',
        'color': 'color',
        'material_name': 'material_name',
        'hc': 'hc',
        'bound': 'bound',
        'hole': 'hole',
        'index': 'index',
        'type': 'type',
        'type_id': 'type_id',
        'leaf': 'leaf',
        'parent': 'parent',
        'visible': 'visible',
        'active': 'active',
        'timestamp': 'timestamp'
    }

    def __init__(self, id=None, name=None, x=None, x_calc=None, y=None, y_calc=None, z=None, z_calc=None, dx=None, dx_calc=None, dy=None, dy_calc=None, dz=None, dz_calc=None, power=None, power_calc=None, sphere=None, material=None, color=None, material_name=None, hc=None, bound=None, hole=None, index=None, type=None, type_id=None, leaf=None, parent=None, visible=None, active=None, timestamp=None, local_vars_configuration=None):  # noqa: E501
        """Box - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._x = None
        self._x_calc = None
        self._y = None
        self._y_calc = None
        self._z = None
        self._z_calc = None
        self._dx = None
        self._dx_calc = None
        self._dy = None
        self._dy_calc = None
        self._dz = None
        self._dz_calc = None
        self._power = None
        self._power_calc = None
        self._sphere = None
        self._material = None
        self._color = None
        self._material_name = None
        self._hc = None
        self._bound = None
        self._hole = None
        self._index = None
        self._type = None
        self._type_id = None
        self._leaf = None
        self._parent = None
        self._visible = None
        self._active = None
        self._timestamp = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.x = x
        if x_calc is not None:
            self.x_calc = x_calc
        self.y = y
        if y_calc is not None:
            self.y_calc = y_calc
        self.z = z
        if z_calc is not None:
            self.z_calc = z_calc
        self.dx = dx
        if dx_calc is not None:
            self.dx_calc = dx_calc
        self.dy = dy
        if dy_calc is not None:
            self.dy_calc = dy_calc
        self.dz = dz
        if dz_calc is not None:
            self.dz_calc = dz_calc
        if power is not None:
            self.power = power
        if power_calc is not None:
            self.power_calc = power_calc
        if sphere is not None:
            self.sphere = sphere
        self.material = material
        if color is not None:
            self.color = color
        if material_name is not None:
            self.material_name = material_name
        self.hc = hc
        if bound is not None:
            self.bound = bound
        if hole is not None:
            self.hole = hole
        self.index = index
        if type is not None:
            self.type = type
        if type_id is not None:
            self.type_id = type_id
        if leaf is not None:
            self.leaf = leaf
        self.parent = parent
        if visible is not None:
            self.visible = visible
        if active is not None:
            self.active = active
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def id(self):
        """Gets the id of this Box.  # noqa: E501


        :return: The id of this Box.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Box.


        :param id: The id of this Box.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Box.  # noqa: E501


        :return: The name of this Box.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Box.


        :param name: The name of this Box.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def x(self):
        """Gets the x of this Box.  # noqa: E501


        :return: The x of this Box.  # noqa: E501
        :rtype: str
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this Box.


        :param x: The x of this Box.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and x is None:  # noqa: E501
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                x is not None and len(x) < 1):
            raise ValueError("Invalid value for `x`, length must be greater than or equal to `1`")  # noqa: E501

        self._x = x

    @property
    def x_calc(self):
        """Gets the x_calc of this Box.  # noqa: E501


        :return: The x_calc of this Box.  # noqa: E501
        :rtype: float
        """
        return self._x_calc

    @x_calc.setter
    def x_calc(self, x_calc):
        """Sets the x_calc of this Box.


        :param x_calc: The x_calc of this Box.  # noqa: E501
        :type: float
        """

        self._x_calc = x_calc

    @property
    def y(self):
        """Gets the y of this Box.  # noqa: E501


        :return: The y of this Box.  # noqa: E501
        :rtype: str
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this Box.


        :param y: The y of this Box.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and y is None:  # noqa: E501
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                y is not None and len(y) < 1):
            raise ValueError("Invalid value for `y`, length must be greater than or equal to `1`")  # noqa: E501

        self._y = y

    @property
    def y_calc(self):
        """Gets the y_calc of this Box.  # noqa: E501


        :return: The y_calc of this Box.  # noqa: E501
        :rtype: float
        """
        return self._y_calc

    @y_calc.setter
    def y_calc(self, y_calc):
        """Sets the y_calc of this Box.


        :param y_calc: The y_calc of this Box.  # noqa: E501
        :type: float
        """

        self._y_calc = y_calc

    @property
    def z(self):
        """Gets the z of this Box.  # noqa: E501


        :return: The z of this Box.  # noqa: E501
        :rtype: str
        """
        return self._z

    @z.setter
    def z(self, z):
        """Sets the z of this Box.


        :param z: The z of this Box.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and z is None:  # noqa: E501
            raise ValueError("Invalid value for `z`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                z is not None and len(z) < 1):
            raise ValueError("Invalid value for `z`, length must be greater than or equal to `1`")  # noqa: E501

        self._z = z

    @property
    def z_calc(self):
        """Gets the z_calc of this Box.  # noqa: E501


        :return: The z_calc of this Box.  # noqa: E501
        :rtype: float
        """
        return self._z_calc

    @z_calc.setter
    def z_calc(self, z_calc):
        """Sets the z_calc of this Box.


        :param z_calc: The z_calc of this Box.  # noqa: E501
        :type: float
        """

        self._z_calc = z_calc

    @property
    def dx(self):
        """Gets the dx of this Box.  # noqa: E501


        :return: The dx of this Box.  # noqa: E501
        :rtype: str
        """
        return self._dx

    @dx.setter
    def dx(self, dx):
        """Sets the dx of this Box.


        :param dx: The dx of this Box.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and dx is None:  # noqa: E501
            raise ValueError("Invalid value for `dx`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                dx is not None and len(dx) < 1):
            raise ValueError("Invalid value for `dx`, length must be greater than or equal to `1`")  # noqa: E501

        self._dx = dx

    @property
    def dx_calc(self):
        """Gets the dx_calc of this Box.  # noqa: E501


        :return: The dx_calc of this Box.  # noqa: E501
        :rtype: float
        """
        return self._dx_calc

    @dx_calc.setter
    def dx_calc(self, dx_calc):
        """Sets the dx_calc of this Box.


        :param dx_calc: The dx_calc of this Box.  # noqa: E501
        :type: float
        """

        self._dx_calc = dx_calc

    @property
    def dy(self):
        """Gets the dy of this Box.  # noqa: E501


        :return: The dy of this Box.  # noqa: E501
        :rtype: str
        """
        return self._dy

    @dy.setter
    def dy(self, dy):
        """Sets the dy of this Box.


        :param dy: The dy of this Box.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and dy is None:  # noqa: E501
            raise ValueError("Invalid value for `dy`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                dy is not None and len(dy) < 1):
            raise ValueError("Invalid value for `dy`, length must be greater than or equal to `1`")  # noqa: E501

        self._dy = dy

    @property
    def dy_calc(self):
        """Gets the dy_calc of this Box.  # noqa: E501


        :return: The dy_calc of this Box.  # noqa: E501
        :rtype: float
        """
        return self._dy_calc

    @dy_calc.setter
    def dy_calc(self, dy_calc):
        """Sets the dy_calc of this Box.


        :param dy_calc: The dy_calc of this Box.  # noqa: E501
        :type: float
        """

        self._dy_calc = dy_calc

    @property
    def dz(self):
        """Gets the dz of this Box.  # noqa: E501


        :return: The dz of this Box.  # noqa: E501
        :rtype: str
        """
        return self._dz

    @dz.setter
    def dz(self, dz):
        """Sets the dz of this Box.


        :param dz: The dz of this Box.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and dz is None:  # noqa: E501
            raise ValueError("Invalid value for `dz`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                dz is not None and len(dz) < 1):
            raise ValueError("Invalid value for `dz`, length must be greater than or equal to `1`")  # noqa: E501

        self._dz = dz

    @property
    def dz_calc(self):
        """Gets the dz_calc of this Box.  # noqa: E501


        :return: The dz_calc of this Box.  # noqa: E501
        :rtype: float
        """
        return self._dz_calc

    @dz_calc.setter
    def dz_calc(self, dz_calc):
        """Sets the dz_calc of this Box.


        :param dz_calc: The dz_calc of this Box.  # noqa: E501
        :type: float
        """

        self._dz_calc = dz_calc

    @property
    def power(self):
        """Gets the power of this Box.  # noqa: E501


        :return: The power of this Box.  # noqa: E501
        :rtype: str
        """
        return self._power

    @power.setter
    def power(self, power):
        """Sets the power of this Box.


        :param power: The power of this Box.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                power is not None and len(power) < 1):
            raise ValueError("Invalid value for `power`, length must be greater than or equal to `1`")  # noqa: E501

        self._power = power

    @property
    def power_calc(self):
        """Gets the power_calc of this Box.  # noqa: E501


        :return: The power_calc of this Box.  # noqa: E501
        :rtype: float
        """
        return self._power_calc

    @power_calc.setter
    def power_calc(self, power_calc):
        """Sets the power_calc of this Box.


        :param power_calc: The power_calc of this Box.  # noqa: E501
        :type: float
        """

        self._power_calc = power_calc

    @property
    def sphere(self):
        """Gets the sphere of this Box.  # noqa: E501


        :return: The sphere of this Box.  # noqa: E501
        :rtype: bool
        """
        return self._sphere

    @sphere.setter
    def sphere(self, sphere):
        """Sets the sphere of this Box.


        :param sphere: The sphere of this Box.  # noqa: E501
        :type: bool
        """

        self._sphere = sphere

    @property
    def material(self):
        """Gets the material of this Box.  # noqa: E501


        :return: The material of this Box.  # noqa: E501
        :rtype: int
        """
        return self._material

    @material.setter
    def material(self, material):
        """Sets the material of this Box.


        :param material: The material of this Box.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and material is None:  # noqa: E501
            raise ValueError("Invalid value for `material`, must not be `None`")  # noqa: E501

        self._material = material

    @property
    def color(self):
        """Gets the color of this Box.  # noqa: E501


        :return: The color of this Box.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this Box.


        :param color: The color of this Box.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def material_name(self):
        """Gets the material_name of this Box.  # noqa: E501


        :return: The material_name of this Box.  # noqa: E501
        :rtype: str
        """
        return self._material_name

    @material_name.setter
    def material_name(self, material_name):
        """Sets the material_name of this Box.


        :param material_name: The material_name of this Box.  # noqa: E501
        :type: str
        """

        self._material_name = material_name

    @property
    def hc(self):
        """Gets the hc of this Box.  # noqa: E501


        :return: The hc of this Box.  # noqa: E501
        :rtype: str
        """
        return self._hc

    @hc.setter
    def hc(self, hc):
        """Sets the hc of this Box.


        :param hc: The hc of this Box.  # noqa: E501
        :type: str
        """

        self._hc = hc

    @property
    def bound(self):
        """Gets the bound of this Box.  # noqa: E501


        :return: The bound of this Box.  # noqa: E501
        :rtype: bool
        """
        return self._bound

    @bound.setter
    def bound(self, bound):
        """Sets the bound of this Box.


        :param bound: The bound of this Box.  # noqa: E501
        :type: bool
        """

        self._bound = bound

    @property
    def hole(self):
        """Gets the hole of this Box.  # noqa: E501


        :return: The hole of this Box.  # noqa: E501
        :rtype: bool
        """
        return self._hole

    @hole.setter
    def hole(self, hole):
        """Sets the hole of this Box.


        :param hole: The hole of this Box.  # noqa: E501
        :type: bool
        """

        self._hole = hole

    @property
    def index(self):
        """Gets the index of this Box.  # noqa: E501


        :return: The index of this Box.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this Box.


        :param index: The index of this Box.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and index is None:  # noqa: E501
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index is not None and index > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `index`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index is not None and index < 0):  # noqa: E501
            raise ValueError("Invalid value for `index`, must be a value greater than or equal to `0`")  # noqa: E501

        self._index = index

    @property
    def type(self):
        """Gets the type of this Box.  # noqa: E501


        :return: The type of this Box.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Box.


        :param type: The type of this Box.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def type_id(self):
        """Gets the type_id of this Box.  # noqa: E501


        :return: The type_id of this Box.  # noqa: E501
        :rtype: int
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id):
        """Sets the type_id of this Box.


        :param type_id: The type_id of this Box.  # noqa: E501
        :type: int
        """

        self._type_id = type_id

    @property
    def leaf(self):
        """Gets the leaf of this Box.  # noqa: E501


        :return: The leaf of this Box.  # noqa: E501
        :rtype: bool
        """
        return self._leaf

    @leaf.setter
    def leaf(self, leaf):
        """Sets the leaf of this Box.


        :param leaf: The leaf of this Box.  # noqa: E501
        :type: bool
        """

        self._leaf = leaf

    @property
    def parent(self):
        """Gets the parent of this Box.  # noqa: E501


        :return: The parent of this Box.  # noqa: E501
        :rtype: int
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this Box.


        :param parent: The parent of this Box.  # noqa: E501
        :type: int
        """

        self._parent = parent

    @property
    def visible(self):
        """Gets the visible of this Box.  # noqa: E501


        :return: The visible of this Box.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this Box.


        :param visible: The visible of this Box.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    @property
    def active(self):
        """Gets the active of this Box.  # noqa: E501


        :return: The active of this Box.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this Box.


        :param active: The active of this Box.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def timestamp(self):
        """Gets the timestamp of this Box.  # noqa: E501


        :return: The timestamp of this Box.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Box.


        :param timestamp: The timestamp of this Box.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Box):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Box):
            return True

        return self.to_dict() != other.to_dict()
