# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class Heatsink(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'index': 'int',
        'type': 'str',
        'type_id': 'int',
        'leaf': 'bool',
        'parent': 'int',
        'visible': 'bool',
        'active': 'bool',
        'material': 'int',
        'color': 'str',
        'material_name': 'str',
        'x': 'str',
        'y': 'str',
        'z': 'str',
        'base_dx': 'str',
        'base_dy': 'str',
        'base_dz': 'str',
        'x_calc': 'float',
        'y_calc': 'float',
        'z_calc': 'float',
        'base_dx_calc': 'float',
        'base_dy_calc': 'float',
        'base_dz_calc': 'float',
        'fin_height': 'str',
        'fin_thickness': 'str',
        'fin_count': 'str',
        'fin_height_calc': 'float',
        'fin_thickness_calc': 'float',
        'fin_count_calc': 'int',
        'hc': 'str',
        'bound': 'bool',
        'fin_axis': 'str',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'index': 'index',
        'type': 'type',
        'type_id': 'type_id',
        'leaf': 'leaf',
        'parent': 'parent',
        'visible': 'visible',
        'active': 'active',
        'material': 'material',
        'color': 'color',
        'material_name': 'material_name',
        'x': 'x',
        'y': 'y',
        'z': 'z',
        'base_dx': 'base_dx',
        'base_dy': 'base_dy',
        'base_dz': 'base_dz',
        'x_calc': 'x_calc',
        'y_calc': 'y_calc',
        'z_calc': 'z_calc',
        'base_dx_calc': 'base_dx_calc',
        'base_dy_calc': 'base_dy_calc',
        'base_dz_calc': 'base_dz_calc',
        'fin_height': 'fin_height',
        'fin_thickness': 'fin_thickness',
        'fin_count': 'fin_count',
        'fin_height_calc': 'fin_height_calc',
        'fin_thickness_calc': 'fin_thickness_calc',
        'fin_count_calc': 'fin_count_calc',
        'hc': 'hc',
        'bound': 'bound',
        'fin_axis': 'fin_axis',
        'timestamp': 'timestamp'
    }

    def __init__(self, id=None, name=None, index=None, type=None, type_id=None, leaf=None, parent=None, visible=None, active=None, material=None, color=None, material_name=None, x=None, y=None, z=None, base_dx=None, base_dy=None, base_dz=None, x_calc=None, y_calc=None, z_calc=None, base_dx_calc=None, base_dy_calc=None, base_dz_calc=None, fin_height=None, fin_thickness=None, fin_count=None, fin_height_calc=None, fin_thickness_calc=None, fin_count_calc=None, hc=None, bound=None, fin_axis=None, timestamp=None, local_vars_configuration=None):  # noqa: E501
        """Heatsink - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._index = None
        self._type = None
        self._type_id = None
        self._leaf = None
        self._parent = None
        self._visible = None
        self._active = None
        self._material = None
        self._color = None
        self._material_name = None
        self._x = None
        self._y = None
        self._z = None
        self._base_dx = None
        self._base_dy = None
        self._base_dz = None
        self._x_calc = None
        self._y_calc = None
        self._z_calc = None
        self._base_dx_calc = None
        self._base_dy_calc = None
        self._base_dz_calc = None
        self._fin_height = None
        self._fin_thickness = None
        self._fin_count = None
        self._fin_height_calc = None
        self._fin_thickness_calc = None
        self._fin_count_calc = None
        self._hc = None
        self._bound = None
        self._fin_axis = None
        self._timestamp = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.index = index
        if type is not None:
            self.type = type
        if type_id is not None:
            self.type_id = type_id
        if leaf is not None:
            self.leaf = leaf
        self.parent = parent
        if visible is not None:
            self.visible = visible
        if active is not None:
            self.active = active
        self.material = material
        if color is not None:
            self.color = color
        if material_name is not None:
            self.material_name = material_name
        self.x = x
        self.y = y
        self.z = z
        self.base_dx = base_dx
        self.base_dy = base_dy
        self.base_dz = base_dz
        if x_calc is not None:
            self.x_calc = x_calc
        if y_calc is not None:
            self.y_calc = y_calc
        if z_calc is not None:
            self.z_calc = z_calc
        if base_dx_calc is not None:
            self.base_dx_calc = base_dx_calc
        if base_dy_calc is not None:
            self.base_dy_calc = base_dy_calc
        if base_dz_calc is not None:
            self.base_dz_calc = base_dz_calc
        self.fin_height = fin_height
        self.fin_thickness = fin_thickness
        self.fin_count = fin_count
        if fin_height_calc is not None:
            self.fin_height_calc = fin_height_calc
        if fin_thickness_calc is not None:
            self.fin_thickness_calc = fin_thickness_calc
        if fin_count_calc is not None:
            self.fin_count_calc = fin_count_calc
        self.hc = hc
        if bound is not None:
            self.bound = bound
        self.fin_axis = fin_axis
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def id(self):
        """Gets the id of this Heatsink.  # noqa: E501


        :return: The id of this Heatsink.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Heatsink.


        :param id: The id of this Heatsink.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Heatsink.  # noqa: E501


        :return: The name of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Heatsink.


        :param name: The name of this Heatsink.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def index(self):
        """Gets the index of this Heatsink.  # noqa: E501


        :return: The index of this Heatsink.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this Heatsink.


        :param index: The index of this Heatsink.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and index is None:  # noqa: E501
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index is not None and index > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `index`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index is not None and index < 0):  # noqa: E501
            raise ValueError("Invalid value for `index`, must be a value greater than or equal to `0`")  # noqa: E501

        self._index = index

    @property
    def type(self):
        """Gets the type of this Heatsink.  # noqa: E501


        :return: The type of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Heatsink.


        :param type: The type of this Heatsink.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def type_id(self):
        """Gets the type_id of this Heatsink.  # noqa: E501


        :return: The type_id of this Heatsink.  # noqa: E501
        :rtype: int
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id):
        """Sets the type_id of this Heatsink.


        :param type_id: The type_id of this Heatsink.  # noqa: E501
        :type: int
        """

        self._type_id = type_id

    @property
    def leaf(self):
        """Gets the leaf of this Heatsink.  # noqa: E501


        :return: The leaf of this Heatsink.  # noqa: E501
        :rtype: bool
        """
        return self._leaf

    @leaf.setter
    def leaf(self, leaf):
        """Sets the leaf of this Heatsink.


        :param leaf: The leaf of this Heatsink.  # noqa: E501
        :type: bool
        """

        self._leaf = leaf

    @property
    def parent(self):
        """Gets the parent of this Heatsink.  # noqa: E501


        :return: The parent of this Heatsink.  # noqa: E501
        :rtype: int
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this Heatsink.


        :param parent: The parent of this Heatsink.  # noqa: E501
        :type: int
        """

        self._parent = parent

    @property
    def visible(self):
        """Gets the visible of this Heatsink.  # noqa: E501


        :return: The visible of this Heatsink.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this Heatsink.


        :param visible: The visible of this Heatsink.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    @property
    def active(self):
        """Gets the active of this Heatsink.  # noqa: E501


        :return: The active of this Heatsink.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this Heatsink.


        :param active: The active of this Heatsink.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def material(self):
        """Gets the material of this Heatsink.  # noqa: E501


        :return: The material of this Heatsink.  # noqa: E501
        :rtype: int
        """
        return self._material

    @material.setter
    def material(self, material):
        """Sets the material of this Heatsink.


        :param material: The material of this Heatsink.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and material is None:  # noqa: E501
            raise ValueError("Invalid value for `material`, must not be `None`")  # noqa: E501

        self._material = material

    @property
    def color(self):
        """Gets the color of this Heatsink.  # noqa: E501


        :return: The color of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this Heatsink.


        :param color: The color of this Heatsink.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def material_name(self):
        """Gets the material_name of this Heatsink.  # noqa: E501


        :return: The material_name of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._material_name

    @material_name.setter
    def material_name(self, material_name):
        """Sets the material_name of this Heatsink.


        :param material_name: The material_name of this Heatsink.  # noqa: E501
        :type: str
        """

        self._material_name = material_name

    @property
    def x(self):
        """Gets the x of this Heatsink.  # noqa: E501


        :return: The x of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this Heatsink.


        :param x: The x of this Heatsink.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and x is None:  # noqa: E501
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                x is not None and len(x) < 1):
            raise ValueError("Invalid value for `x`, length must be greater than or equal to `1`")  # noqa: E501

        self._x = x

    @property
    def y(self):
        """Gets the y of this Heatsink.  # noqa: E501


        :return: The y of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this Heatsink.


        :param y: The y of this Heatsink.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and y is None:  # noqa: E501
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                y is not None and len(y) < 1):
            raise ValueError("Invalid value for `y`, length must be greater than or equal to `1`")  # noqa: E501

        self._y = y

    @property
    def z(self):
        """Gets the z of this Heatsink.  # noqa: E501


        :return: The z of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._z

    @z.setter
    def z(self, z):
        """Sets the z of this Heatsink.


        :param z: The z of this Heatsink.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and z is None:  # noqa: E501
            raise ValueError("Invalid value for `z`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                z is not None and len(z) < 1):
            raise ValueError("Invalid value for `z`, length must be greater than or equal to `1`")  # noqa: E501

        self._z = z

    @property
    def base_dx(self):
        """Gets the base_dx of this Heatsink.  # noqa: E501


        :return: The base_dx of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._base_dx

    @base_dx.setter
    def base_dx(self, base_dx):
        """Sets the base_dx of this Heatsink.


        :param base_dx: The base_dx of this Heatsink.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and base_dx is None:  # noqa: E501
            raise ValueError("Invalid value for `base_dx`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                base_dx is not None and len(base_dx) < 1):
            raise ValueError("Invalid value for `base_dx`, length must be greater than or equal to `1`")  # noqa: E501

        self._base_dx = base_dx

    @property
    def base_dy(self):
        """Gets the base_dy of this Heatsink.  # noqa: E501


        :return: The base_dy of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._base_dy

    @base_dy.setter
    def base_dy(self, base_dy):
        """Sets the base_dy of this Heatsink.


        :param base_dy: The base_dy of this Heatsink.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and base_dy is None:  # noqa: E501
            raise ValueError("Invalid value for `base_dy`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                base_dy is not None and len(base_dy) < 1):
            raise ValueError("Invalid value for `base_dy`, length must be greater than or equal to `1`")  # noqa: E501

        self._base_dy = base_dy

    @property
    def base_dz(self):
        """Gets the base_dz of this Heatsink.  # noqa: E501


        :return: The base_dz of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._base_dz

    @base_dz.setter
    def base_dz(self, base_dz):
        """Sets the base_dz of this Heatsink.


        :param base_dz: The base_dz of this Heatsink.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and base_dz is None:  # noqa: E501
            raise ValueError("Invalid value for `base_dz`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                base_dz is not None and len(base_dz) < 1):
            raise ValueError("Invalid value for `base_dz`, length must be greater than or equal to `1`")  # noqa: E501

        self._base_dz = base_dz

    @property
    def x_calc(self):
        """Gets the x_calc of this Heatsink.  # noqa: E501


        :return: The x_calc of this Heatsink.  # noqa: E501
        :rtype: float
        """
        return self._x_calc

    @x_calc.setter
    def x_calc(self, x_calc):
        """Sets the x_calc of this Heatsink.


        :param x_calc: The x_calc of this Heatsink.  # noqa: E501
        :type: float
        """

        self._x_calc = x_calc

    @property
    def y_calc(self):
        """Gets the y_calc of this Heatsink.  # noqa: E501


        :return: The y_calc of this Heatsink.  # noqa: E501
        :rtype: float
        """
        return self._y_calc

    @y_calc.setter
    def y_calc(self, y_calc):
        """Sets the y_calc of this Heatsink.


        :param y_calc: The y_calc of this Heatsink.  # noqa: E501
        :type: float
        """

        self._y_calc = y_calc

    @property
    def z_calc(self):
        """Gets the z_calc of this Heatsink.  # noqa: E501


        :return: The z_calc of this Heatsink.  # noqa: E501
        :rtype: float
        """
        return self._z_calc

    @z_calc.setter
    def z_calc(self, z_calc):
        """Sets the z_calc of this Heatsink.


        :param z_calc: The z_calc of this Heatsink.  # noqa: E501
        :type: float
        """

        self._z_calc = z_calc

    @property
    def base_dx_calc(self):
        """Gets the base_dx_calc of this Heatsink.  # noqa: E501


        :return: The base_dx_calc of this Heatsink.  # noqa: E501
        :rtype: float
        """
        return self._base_dx_calc

    @base_dx_calc.setter
    def base_dx_calc(self, base_dx_calc):
        """Sets the base_dx_calc of this Heatsink.


        :param base_dx_calc: The base_dx_calc of this Heatsink.  # noqa: E501
        :type: float
        """

        self._base_dx_calc = base_dx_calc

    @property
    def base_dy_calc(self):
        """Gets the base_dy_calc of this Heatsink.  # noqa: E501


        :return: The base_dy_calc of this Heatsink.  # noqa: E501
        :rtype: float
        """
        return self._base_dy_calc

    @base_dy_calc.setter
    def base_dy_calc(self, base_dy_calc):
        """Sets the base_dy_calc of this Heatsink.


        :param base_dy_calc: The base_dy_calc of this Heatsink.  # noqa: E501
        :type: float
        """

        self._base_dy_calc = base_dy_calc

    @property
    def base_dz_calc(self):
        """Gets the base_dz_calc of this Heatsink.  # noqa: E501


        :return: The base_dz_calc of this Heatsink.  # noqa: E501
        :rtype: float
        """
        return self._base_dz_calc

    @base_dz_calc.setter
    def base_dz_calc(self, base_dz_calc):
        """Sets the base_dz_calc of this Heatsink.


        :param base_dz_calc: The base_dz_calc of this Heatsink.  # noqa: E501
        :type: float
        """

        self._base_dz_calc = base_dz_calc

    @property
    def fin_height(self):
        """Gets the fin_height of this Heatsink.  # noqa: E501


        :return: The fin_height of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._fin_height

    @fin_height.setter
    def fin_height(self, fin_height):
        """Sets the fin_height of this Heatsink.


        :param fin_height: The fin_height of this Heatsink.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and fin_height is None:  # noqa: E501
            raise ValueError("Invalid value for `fin_height`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                fin_height is not None and len(fin_height) < 1):
            raise ValueError("Invalid value for `fin_height`, length must be greater than or equal to `1`")  # noqa: E501

        self._fin_height = fin_height

    @property
    def fin_thickness(self):
        """Gets the fin_thickness of this Heatsink.  # noqa: E501


        :return: The fin_thickness of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._fin_thickness

    @fin_thickness.setter
    def fin_thickness(self, fin_thickness):
        """Sets the fin_thickness of this Heatsink.


        :param fin_thickness: The fin_thickness of this Heatsink.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and fin_thickness is None:  # noqa: E501
            raise ValueError("Invalid value for `fin_thickness`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                fin_thickness is not None and len(fin_thickness) < 1):
            raise ValueError("Invalid value for `fin_thickness`, length must be greater than or equal to `1`")  # noqa: E501

        self._fin_thickness = fin_thickness

    @property
    def fin_count(self):
        """Gets the fin_count of this Heatsink.  # noqa: E501


        :return: The fin_count of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._fin_count

    @fin_count.setter
    def fin_count(self, fin_count):
        """Sets the fin_count of this Heatsink.


        :param fin_count: The fin_count of this Heatsink.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and fin_count is None:  # noqa: E501
            raise ValueError("Invalid value for `fin_count`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                fin_count is not None and len(fin_count) < 1):
            raise ValueError("Invalid value for `fin_count`, length must be greater than or equal to `1`")  # noqa: E501

        self._fin_count = fin_count

    @property
    def fin_height_calc(self):
        """Gets the fin_height_calc of this Heatsink.  # noqa: E501


        :return: The fin_height_calc of this Heatsink.  # noqa: E501
        :rtype: float
        """
        return self._fin_height_calc

    @fin_height_calc.setter
    def fin_height_calc(self, fin_height_calc):
        """Sets the fin_height_calc of this Heatsink.


        :param fin_height_calc: The fin_height_calc of this Heatsink.  # noqa: E501
        :type: float
        """

        self._fin_height_calc = fin_height_calc

    @property
    def fin_thickness_calc(self):
        """Gets the fin_thickness_calc of this Heatsink.  # noqa: E501


        :return: The fin_thickness_calc of this Heatsink.  # noqa: E501
        :rtype: float
        """
        return self._fin_thickness_calc

    @fin_thickness_calc.setter
    def fin_thickness_calc(self, fin_thickness_calc):
        """Sets the fin_thickness_calc of this Heatsink.


        :param fin_thickness_calc: The fin_thickness_calc of this Heatsink.  # noqa: E501
        :type: float
        """

        self._fin_thickness_calc = fin_thickness_calc

    @property
    def fin_count_calc(self):
        """Gets the fin_count_calc of this Heatsink.  # noqa: E501


        :return: The fin_count_calc of this Heatsink.  # noqa: E501
        :rtype: int
        """
        return self._fin_count_calc

    @fin_count_calc.setter
    def fin_count_calc(self, fin_count_calc):
        """Sets the fin_count_calc of this Heatsink.


        :param fin_count_calc: The fin_count_calc of this Heatsink.  # noqa: E501
        :type: int
        """

        self._fin_count_calc = fin_count_calc

    @property
    def hc(self):
        """Gets the hc of this Heatsink.  # noqa: E501


        :return: The hc of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._hc

    @hc.setter
    def hc(self, hc):
        """Sets the hc of this Heatsink.


        :param hc: The hc of this Heatsink.  # noqa: E501
        :type: str
        """

        self._hc = hc

    @property
    def bound(self):
        """Gets the bound of this Heatsink.  # noqa: E501


        :return: The bound of this Heatsink.  # noqa: E501
        :rtype: bool
        """
        return self._bound

    @bound.setter
    def bound(self, bound):
        """Sets the bound of this Heatsink.


        :param bound: The bound of this Heatsink.  # noqa: E501
        :type: bool
        """

        self._bound = bound

    @property
    def fin_axis(self):
        """Gets the fin_axis of this Heatsink.  # noqa: E501


        :return: The fin_axis of this Heatsink.  # noqa: E501
        :rtype: str
        """
        return self._fin_axis

    @fin_axis.setter
    def fin_axis(self, fin_axis):
        """Sets the fin_axis of this Heatsink.


        :param fin_axis: The fin_axis of this Heatsink.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and fin_axis is None:  # noqa: E501
            raise ValueError("Invalid value for `fin_axis`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                fin_axis is not None and len(fin_axis) > 1):
            raise ValueError("Invalid value for `fin_axis`, length must be less than or equal to `1`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                fin_axis is not None and len(fin_axis) < 1):
            raise ValueError("Invalid value for `fin_axis`, length must be greater than or equal to `1`")  # noqa: E501

        self._fin_axis = fin_axis

    @property
    def timestamp(self):
        """Gets the timestamp of this Heatsink.  # noqa: E501


        :return: The timestamp of this Heatsink.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Heatsink.


        :param timestamp: The timestamp of this Heatsink.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Heatsink):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Heatsink):
            return True

        return self.to_dict() != other.to_dict()
