# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class LibraryLibraryidPermissionsPermissions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'owner': 'bool',
        'editor': 'bool',
        'viewer': 'bool'
    }

    attribute_map = {
        'owner': 'owner',
        'editor': 'editor',
        'viewer': 'viewer'
    }

    def __init__(self, owner=None, editor=None, viewer=None, local_vars_configuration=None):  # noqa: E501
        """LibraryLibraryidPermissionsPermissions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._owner = None
        self._editor = None
        self._viewer = None
        self.discriminator = None

        if owner is not None:
            self.owner = owner
        if editor is not None:
            self.editor = editor
        if viewer is not None:
            self.viewer = viewer

    @property
    def owner(self):
        """Gets the owner of this LibraryLibraryidPermissionsPermissions.  # noqa: E501


        :return: The owner of this LibraryLibraryidPermissionsPermissions.  # noqa: E501
        :rtype: bool
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this LibraryLibraryidPermissionsPermissions.


        :param owner: The owner of this LibraryLibraryidPermissionsPermissions.  # noqa: E501
        :type: bool
        """

        self._owner = owner

    @property
    def editor(self):
        """Gets the editor of this LibraryLibraryidPermissionsPermissions.  # noqa: E501


        :return: The editor of this LibraryLibraryidPermissionsPermissions.  # noqa: E501
        :rtype: bool
        """
        return self._editor

    @editor.setter
    def editor(self, editor):
        """Sets the editor of this LibraryLibraryidPermissionsPermissions.


        :param editor: The editor of this LibraryLibraryidPermissionsPermissions.  # noqa: E501
        :type: bool
        """

        self._editor = editor

    @property
    def viewer(self):
        """Gets the viewer of this LibraryLibraryidPermissionsPermissions.  # noqa: E501


        :return: The viewer of this LibraryLibraryidPermissionsPermissions.  # noqa: E501
        :rtype: bool
        """
        return self._viewer

    @viewer.setter
    def viewer(self, viewer):
        """Sets the viewer of this LibraryLibraryidPermissionsPermissions.


        :param viewer: The viewer of this LibraryLibraryidPermissionsPermissions.  # noqa: E501
        :type: bool
        """

        self._viewer = viewer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LibraryLibraryidPermissionsPermissions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LibraryLibraryidPermissionsPermissions):
            return True

        return self.to_dict() != other.to_dict()
