# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class Library(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'created_on': 'datetime',
        'created_by': 'int',
        'owner': 'bool',
        'edit': 'bool',
        'view': 'bool',
        'materials': 'list[Material]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'created_on': 'created_on',
        'created_by': 'created_by',
        'owner': 'owner',
        'edit': 'edit',
        'view': 'view',
        'materials': 'materials'
    }

    def __init__(self, id=None, name=None, created_on=None, created_by=None, owner=None, edit=None, view=None, materials=None, local_vars_configuration=None):  # noqa: E501
        """Library - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._created_on = None
        self._created_by = None
        self._owner = None
        self._edit = None
        self._view = None
        self._materials = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        if created_on is not None:
            self.created_on = created_on
        if created_by is not None:
            self.created_by = created_by
        if owner is not None:
            self.owner = owner
        if edit is not None:
            self.edit = edit
        if view is not None:
            self.view = view
        if materials is not None:
            self.materials = materials

    @property
    def id(self):
        """Gets the id of this Library.  # noqa: E501


        :return: The id of this Library.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Library.


        :param id: The id of this Library.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Library.  # noqa: E501


        :return: The name of this Library.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Library.


        :param name: The name of this Library.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def created_on(self):
        """Gets the created_on of this Library.  # noqa: E501


        :return: The created_on of this Library.  # noqa: E501
        :rtype: datetime
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """Sets the created_on of this Library.


        :param created_on: The created_on of this Library.  # noqa: E501
        :type: datetime
        """

        self._created_on = created_on

    @property
    def created_by(self):
        """Gets the created_by of this Library.  # noqa: E501


        :return: The created_by of this Library.  # noqa: E501
        :rtype: int
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Library.


        :param created_by: The created_by of this Library.  # noqa: E501
        :type: int
        """

        self._created_by = created_by

    @property
    def owner(self):
        """Gets the owner of this Library.  # noqa: E501


        :return: The owner of this Library.  # noqa: E501
        :rtype: bool
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Library.


        :param owner: The owner of this Library.  # noqa: E501
        :type: bool
        """

        self._owner = owner

    @property
    def edit(self):
        """Gets the edit of this Library.  # noqa: E501


        :return: The edit of this Library.  # noqa: E501
        :rtype: bool
        """
        return self._edit

    @edit.setter
    def edit(self, edit):
        """Sets the edit of this Library.


        :param edit: The edit of this Library.  # noqa: E501
        :type: bool
        """

        self._edit = edit

    @property
    def view(self):
        """Gets the view of this Library.  # noqa: E501


        :return: The view of this Library.  # noqa: E501
        :rtype: bool
        """
        return self._view

    @view.setter
    def view(self, view):
        """Sets the view of this Library.


        :param view: The view of this Library.  # noqa: E501
        :type: bool
        """

        self._view = view

    @property
    def materials(self):
        """Gets the materials of this Library.  # noqa: E501


        :return: The materials of this Library.  # noqa: E501
        :rtype: list[Material]
        """
        return self._materials

    @materials.setter
    def materials(self, materials):
        """Sets the materials of this Library.


        :param materials: The materials of this Library.  # noqa: E501
        :type: list[Material]
        """

        self._materials = materials

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Library):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Library):
            return True

        return self.to_dict() != other.to_dict()
