# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class Material(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'library_id': 'str',
        'name': 'str',
        'color': 'str',
        'anisotropic': 'bool',
        'conductivity': 'float',
        'conductivity_y': 'float',
        'conductivity_z': 'float',
        'density': 'float',
        'specific_heat': 'float'
    }

    attribute_map = {
        'id': 'id',
        'library_id': 'library_id',
        'name': 'name',
        'color': 'color',
        'anisotropic': 'anisotropic',
        'conductivity': 'conductivity',
        'conductivity_y': 'conductivity_y',
        'conductivity_z': 'conductivity_z',
        'density': 'density',
        'specific_heat': 'specific_heat'
    }

    def __init__(self, id=None, library_id=None, name=None, color=None, anisotropic=None, conductivity=None, conductivity_y=None, conductivity_z=None, density=None, specific_heat=None, local_vars_configuration=None):  # noqa: E501
        """Material - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._library_id = None
        self._name = None
        self._color = None
        self._anisotropic = None
        self._conductivity = None
        self._conductivity_y = None
        self._conductivity_z = None
        self._density = None
        self._specific_heat = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if library_id is not None:
            self.library_id = library_id
        self.name = name
        self.color = color
        if anisotropic is not None:
            self.anisotropic = anisotropic
        self.conductivity = conductivity
        self.conductivity_y = conductivity_y
        self.conductivity_z = conductivity_z
        self.density = density
        self.specific_heat = specific_heat

    @property
    def id(self):
        """Gets the id of this Material.  # noqa: E501


        :return: The id of this Material.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Material.


        :param id: The id of this Material.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def library_id(self):
        """Gets the library_id of this Material.  # noqa: E501


        :return: The library_id of this Material.  # noqa: E501
        :rtype: str
        """
        return self._library_id

    @library_id.setter
    def library_id(self, library_id):
        """Sets the library_id of this Material.


        :param library_id: The library_id of this Material.  # noqa: E501
        :type: str
        """

        self._library_id = library_id

    @property
    def name(self):
        """Gets the name of this Material.  # noqa: E501


        :return: The name of this Material.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Material.


        :param name: The name of this Material.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def color(self):
        """Gets the color of this Material.  # noqa: E501


        :return: The color of this Material.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this Material.


        :param color: The color of this Material.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and color is None:  # noqa: E501
            raise ValueError("Invalid value for `color`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                color is not None and len(color) < 1):
            raise ValueError("Invalid value for `color`, length must be greater than or equal to `1`")  # noqa: E501

        self._color = color

    @property
    def anisotropic(self):
        """Gets the anisotropic of this Material.  # noqa: E501


        :return: The anisotropic of this Material.  # noqa: E501
        :rtype: bool
        """
        return self._anisotropic

    @anisotropic.setter
    def anisotropic(self, anisotropic):
        """Sets the anisotropic of this Material.


        :param anisotropic: The anisotropic of this Material.  # noqa: E501
        :type: bool
        """

        self._anisotropic = anisotropic

    @property
    def conductivity(self):
        """Gets the conductivity of this Material.  # noqa: E501


        :return: The conductivity of this Material.  # noqa: E501
        :rtype: float
        """
        return self._conductivity

    @conductivity.setter
    def conductivity(self, conductivity):
        """Sets the conductivity of this Material.


        :param conductivity: The conductivity of this Material.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and conductivity is None:  # noqa: E501
            raise ValueError("Invalid value for `conductivity`, must not be `None`")  # noqa: E501

        self._conductivity = conductivity

    @property
    def conductivity_y(self):
        """Gets the conductivity_y of this Material.  # noqa: E501


        :return: The conductivity_y of this Material.  # noqa: E501
        :rtype: float
        """
        return self._conductivity_y

    @conductivity_y.setter
    def conductivity_y(self, conductivity_y):
        """Sets the conductivity_y of this Material.


        :param conductivity_y: The conductivity_y of this Material.  # noqa: E501
        :type: float
        """

        self._conductivity_y = conductivity_y

    @property
    def conductivity_z(self):
        """Gets the conductivity_z of this Material.  # noqa: E501


        :return: The conductivity_z of this Material.  # noqa: E501
        :rtype: float
        """
        return self._conductivity_z

    @conductivity_z.setter
    def conductivity_z(self, conductivity_z):
        """Sets the conductivity_z of this Material.


        :param conductivity_z: The conductivity_z of this Material.  # noqa: E501
        :type: float
        """

        self._conductivity_z = conductivity_z

    @property
    def density(self):
        """Gets the density of this Material.  # noqa: E501


        :return: The density of this Material.  # noqa: E501
        :rtype: float
        """
        return self._density

    @density.setter
    def density(self, density):
        """Sets the density of this Material.


        :param density: The density of this Material.  # noqa: E501
        :type: float
        """

        self._density = density

    @property
    def specific_heat(self):
        """Gets the specific_heat of this Material.  # noqa: E501


        :return: The specific_heat of this Material.  # noqa: E501
        :rtype: float
        """
        return self._specific_heat

    @specific_heat.setter
    def specific_heat(self, specific_heat):
        """Sets the specific_heat of this Material.


        :param specific_heat: The specific_heat of this Material.  # noqa: E501
        :type: float
        """

        self._specific_heat = specific_heat

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Material):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Material):
            return True

        return self.to_dict() != other.to_dict()
