# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class NormalDist(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'mean': 'float',
        'stddev': 'float',
        'min': 'float',
        'max': 'float',
        'count': 'int'
    }

    attribute_map = {
        'mean': 'mean',
        'stddev': 'stddev',
        'min': 'min',
        'max': 'max',
        'count': 'count'
    }

    def __init__(self, mean=None, stddev=None, min=None, max=None, count=None, local_vars_configuration=None):  # noqa: E501
        """NormalDist - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._mean = None
        self._stddev = None
        self._min = None
        self._max = None
        self._count = None
        self.discriminator = None

        self.mean = mean
        self.stddev = stddev
        self.min = min
        self.max = max
        self.count = count

    @property
    def mean(self):
        """Gets the mean of this NormalDist.  # noqa: E501


        :return: The mean of this NormalDist.  # noqa: E501
        :rtype: float
        """
        return self._mean

    @mean.setter
    def mean(self, mean):
        """Sets the mean of this NormalDist.


        :param mean: The mean of this NormalDist.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and mean is None:  # noqa: E501
            raise ValueError("Invalid value for `mean`, must not be `None`")  # noqa: E501

        self._mean = mean

    @property
    def stddev(self):
        """Gets the stddev of this NormalDist.  # noqa: E501


        :return: The stddev of this NormalDist.  # noqa: E501
        :rtype: float
        """
        return self._stddev

    @stddev.setter
    def stddev(self, stddev):
        """Sets the stddev of this NormalDist.


        :param stddev: The stddev of this NormalDist.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and stddev is None:  # noqa: E501
            raise ValueError("Invalid value for `stddev`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                stddev is not None and stddev < 0):  # noqa: E501
            raise ValueError("Invalid value for `stddev`, must be a value greater than or equal to `0`")  # noqa: E501

        self._stddev = stddev

    @property
    def min(self):
        """Gets the min of this NormalDist.  # noqa: E501


        :return: The min of this NormalDist.  # noqa: E501
        :rtype: float
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this NormalDist.


        :param min: The min of this NormalDist.  # noqa: E501
        :type: float
        """

        self._min = min

    @property
    def max(self):
        """Gets the max of this NormalDist.  # noqa: E501


        :return: The max of this NormalDist.  # noqa: E501
        :rtype: float
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this NormalDist.


        :param max: The max of this NormalDist.  # noqa: E501
        :type: float
        """

        self._max = max

    @property
    def count(self):
        """Gets the count of this NormalDist.  # noqa: E501


        :return: The count of this NormalDist.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this NormalDist.


        :param count: The count of this NormalDist.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and count is None:  # noqa: E501
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                count is not None and count < 1):  # noqa: E501
            raise ValueError("Invalid value for `count`, must be a value greater than or equal to `1`")  # noqa: E501

        self._count = count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NormalDist):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NormalDist):
            return True

        return self.to_dict() != other.to_dict()
