# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class PCB(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'index': 'int',
        'type': 'str',
        'type_id': 'int',
        'leaf': 'bool',
        'parent': 'int',
        'visible': 'bool',
        'active': 'bool',
        'x': 'str',
        'y': 'str',
        'z': 'str',
        'dx': 'str',
        'dy': 'str',
        'dz': 'float',
        'x_calc': 'float',
        'y_calc': 'float',
        'z_calc': 'float',
        'dx_calc': 'float',
        'dy_calc': 'float',
        'dz_calc': 'float',
        'auto_via': 'bool',
        'hc': 'str',
        'layers': 'list[PCBLayer]',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'index': 'index',
        'type': 'type',
        'type_id': 'type_id',
        'leaf': 'leaf',
        'parent': 'parent',
        'visible': 'visible',
        'active': 'active',
        'x': 'x',
        'y': 'y',
        'z': 'z',
        'dx': 'dx',
        'dy': 'dy',
        'dz': 'dz',
        'x_calc': 'x_calc',
        'y_calc': 'y_calc',
        'z_calc': 'z_calc',
        'dx_calc': 'dx_calc',
        'dy_calc': 'dy_calc',
        'dz_calc': 'dz_calc',
        'auto_via': 'auto_via',
        'hc': 'hc',
        'layers': 'layers',
        'timestamp': 'timestamp'
    }

    def __init__(self, id=None, name=None, index=None, type=None, type_id=None, leaf=None, parent=None, visible=None, active=None, x=None, y=None, z=None, dx=None, dy=None, dz=None, x_calc=None, y_calc=None, z_calc=None, dx_calc=None, dy_calc=None, dz_calc=None, auto_via=None, hc=None, layers=None, timestamp=None, local_vars_configuration=None):  # noqa: E501
        """PCB - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._index = None
        self._type = None
        self._type_id = None
        self._leaf = None
        self._parent = None
        self._visible = None
        self._active = None
        self._x = None
        self._y = None
        self._z = None
        self._dx = None
        self._dy = None
        self._dz = None
        self._x_calc = None
        self._y_calc = None
        self._z_calc = None
        self._dx_calc = None
        self._dy_calc = None
        self._dz_calc = None
        self._auto_via = None
        self._hc = None
        self._layers = None
        self._timestamp = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.index = index
        if type is not None:
            self.type = type
        if type_id is not None:
            self.type_id = type_id
        if leaf is not None:
            self.leaf = leaf
        self.parent = parent
        if visible is not None:
            self.visible = visible
        if active is not None:
            self.active = active
        self.x = x
        self.y = y
        self.z = z
        self.dx = dx
        self.dy = dy
        if dz is not None:
            self.dz = dz
        if x_calc is not None:
            self.x_calc = x_calc
        if y_calc is not None:
            self.y_calc = y_calc
        if z_calc is not None:
            self.z_calc = z_calc
        if dx_calc is not None:
            self.dx_calc = dx_calc
        if dy_calc is not None:
            self.dy_calc = dy_calc
        if dz_calc is not None:
            self.dz_calc = dz_calc
        if auto_via is not None:
            self.auto_via = auto_via
        self.hc = hc
        self.layers = layers
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def id(self):
        """Gets the id of this PCB.  # noqa: E501


        :return: The id of this PCB.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PCB.


        :param id: The id of this PCB.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this PCB.  # noqa: E501


        :return: The name of this PCB.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PCB.


        :param name: The name of this PCB.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def index(self):
        """Gets the index of this PCB.  # noqa: E501


        :return: The index of this PCB.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this PCB.


        :param index: The index of this PCB.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and index is None:  # noqa: E501
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index is not None and index > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `index`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index is not None and index < 0):  # noqa: E501
            raise ValueError("Invalid value for `index`, must be a value greater than or equal to `0`")  # noqa: E501

        self._index = index

    @property
    def type(self):
        """Gets the type of this PCB.  # noqa: E501


        :return: The type of this PCB.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PCB.


        :param type: The type of this PCB.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def type_id(self):
        """Gets the type_id of this PCB.  # noqa: E501


        :return: The type_id of this PCB.  # noqa: E501
        :rtype: int
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id):
        """Sets the type_id of this PCB.


        :param type_id: The type_id of this PCB.  # noqa: E501
        :type: int
        """

        self._type_id = type_id

    @property
    def leaf(self):
        """Gets the leaf of this PCB.  # noqa: E501


        :return: The leaf of this PCB.  # noqa: E501
        :rtype: bool
        """
        return self._leaf

    @leaf.setter
    def leaf(self, leaf):
        """Sets the leaf of this PCB.


        :param leaf: The leaf of this PCB.  # noqa: E501
        :type: bool
        """

        self._leaf = leaf

    @property
    def parent(self):
        """Gets the parent of this PCB.  # noqa: E501


        :return: The parent of this PCB.  # noqa: E501
        :rtype: int
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this PCB.


        :param parent: The parent of this PCB.  # noqa: E501
        :type: int
        """

        self._parent = parent

    @property
    def visible(self):
        """Gets the visible of this PCB.  # noqa: E501


        :return: The visible of this PCB.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this PCB.


        :param visible: The visible of this PCB.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    @property
    def active(self):
        """Gets the active of this PCB.  # noqa: E501


        :return: The active of this PCB.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this PCB.


        :param active: The active of this PCB.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def x(self):
        """Gets the x of this PCB.  # noqa: E501


        :return: The x of this PCB.  # noqa: E501
        :rtype: str
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this PCB.


        :param x: The x of this PCB.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and x is None:  # noqa: E501
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                x is not None and len(x) < 1):
            raise ValueError("Invalid value for `x`, length must be greater than or equal to `1`")  # noqa: E501

        self._x = x

    @property
    def y(self):
        """Gets the y of this PCB.  # noqa: E501


        :return: The y of this PCB.  # noqa: E501
        :rtype: str
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this PCB.


        :param y: The y of this PCB.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and y is None:  # noqa: E501
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                y is not None and len(y) < 1):
            raise ValueError("Invalid value for `y`, length must be greater than or equal to `1`")  # noqa: E501

        self._y = y

    @property
    def z(self):
        """Gets the z of this PCB.  # noqa: E501


        :return: The z of this PCB.  # noqa: E501
        :rtype: str
        """
        return self._z

    @z.setter
    def z(self, z):
        """Sets the z of this PCB.


        :param z: The z of this PCB.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and z is None:  # noqa: E501
            raise ValueError("Invalid value for `z`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                z is not None and len(z) < 1):
            raise ValueError("Invalid value for `z`, length must be greater than or equal to `1`")  # noqa: E501

        self._z = z

    @property
    def dx(self):
        """Gets the dx of this PCB.  # noqa: E501


        :return: The dx of this PCB.  # noqa: E501
        :rtype: str
        """
        return self._dx

    @dx.setter
    def dx(self, dx):
        """Sets the dx of this PCB.


        :param dx: The dx of this PCB.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and dx is None:  # noqa: E501
            raise ValueError("Invalid value for `dx`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                dx is not None and len(dx) < 1):
            raise ValueError("Invalid value for `dx`, length must be greater than or equal to `1`")  # noqa: E501

        self._dx = dx

    @property
    def dy(self):
        """Gets the dy of this PCB.  # noqa: E501


        :return: The dy of this PCB.  # noqa: E501
        :rtype: str
        """
        return self._dy

    @dy.setter
    def dy(self, dy):
        """Sets the dy of this PCB.


        :param dy: The dy of this PCB.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and dy is None:  # noqa: E501
            raise ValueError("Invalid value for `dy`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                dy is not None and len(dy) < 1):
            raise ValueError("Invalid value for `dy`, length must be greater than or equal to `1`")  # noqa: E501

        self._dy = dy

    @property
    def dz(self):
        """Gets the dz of this PCB.  # noqa: E501


        :return: The dz of this PCB.  # noqa: E501
        :rtype: float
        """
        return self._dz

    @dz.setter
    def dz(self, dz):
        """Sets the dz of this PCB.


        :param dz: The dz of this PCB.  # noqa: E501
        :type: float
        """

        self._dz = dz

    @property
    def x_calc(self):
        """Gets the x_calc of this PCB.  # noqa: E501


        :return: The x_calc of this PCB.  # noqa: E501
        :rtype: float
        """
        return self._x_calc

    @x_calc.setter
    def x_calc(self, x_calc):
        """Sets the x_calc of this PCB.


        :param x_calc: The x_calc of this PCB.  # noqa: E501
        :type: float
        """

        self._x_calc = x_calc

    @property
    def y_calc(self):
        """Gets the y_calc of this PCB.  # noqa: E501


        :return: The y_calc of this PCB.  # noqa: E501
        :rtype: float
        """
        return self._y_calc

    @y_calc.setter
    def y_calc(self, y_calc):
        """Sets the y_calc of this PCB.


        :param y_calc: The y_calc of this PCB.  # noqa: E501
        :type: float
        """

        self._y_calc = y_calc

    @property
    def z_calc(self):
        """Gets the z_calc of this PCB.  # noqa: E501


        :return: The z_calc of this PCB.  # noqa: E501
        :rtype: float
        """
        return self._z_calc

    @z_calc.setter
    def z_calc(self, z_calc):
        """Sets the z_calc of this PCB.


        :param z_calc: The z_calc of this PCB.  # noqa: E501
        :type: float
        """

        self._z_calc = z_calc

    @property
    def dx_calc(self):
        """Gets the dx_calc of this PCB.  # noqa: E501


        :return: The dx_calc of this PCB.  # noqa: E501
        :rtype: float
        """
        return self._dx_calc

    @dx_calc.setter
    def dx_calc(self, dx_calc):
        """Sets the dx_calc of this PCB.


        :param dx_calc: The dx_calc of this PCB.  # noqa: E501
        :type: float
        """

        self._dx_calc = dx_calc

    @property
    def dy_calc(self):
        """Gets the dy_calc of this PCB.  # noqa: E501


        :return: The dy_calc of this PCB.  # noqa: E501
        :rtype: float
        """
        return self._dy_calc

    @dy_calc.setter
    def dy_calc(self, dy_calc):
        """Sets the dy_calc of this PCB.


        :param dy_calc: The dy_calc of this PCB.  # noqa: E501
        :type: float
        """

        self._dy_calc = dy_calc

    @property
    def dz_calc(self):
        """Gets the dz_calc of this PCB.  # noqa: E501


        :return: The dz_calc of this PCB.  # noqa: E501
        :rtype: float
        """
        return self._dz_calc

    @dz_calc.setter
    def dz_calc(self, dz_calc):
        """Sets the dz_calc of this PCB.


        :param dz_calc: The dz_calc of this PCB.  # noqa: E501
        :type: float
        """

        self._dz_calc = dz_calc

    @property
    def auto_via(self):
        """Gets the auto_via of this PCB.  # noqa: E501


        :return: The auto_via of this PCB.  # noqa: E501
        :rtype: bool
        """
        return self._auto_via

    @auto_via.setter
    def auto_via(self, auto_via):
        """Sets the auto_via of this PCB.


        :param auto_via: The auto_via of this PCB.  # noqa: E501
        :type: bool
        """

        self._auto_via = auto_via

    @property
    def hc(self):
        """Gets the hc of this PCB.  # noqa: E501


        :return: The hc of this PCB.  # noqa: E501
        :rtype: str
        """
        return self._hc

    @hc.setter
    def hc(self, hc):
        """Sets the hc of this PCB.


        :param hc: The hc of this PCB.  # noqa: E501
        :type: str
        """

        self._hc = hc

    @property
    def layers(self):
        """Gets the layers of this PCB.  # noqa: E501


        :return: The layers of this PCB.  # noqa: E501
        :rtype: list[PCBLayer]
        """
        return self._layers

    @layers.setter
    def layers(self, layers):
        """Sets the layers of this PCB.


        :param layers: The layers of this PCB.  # noqa: E501
        :type: list[PCBLayer]
        """
        if self.local_vars_configuration.client_side_validation and layers is None:  # noqa: E501
            raise ValueError("Invalid value for `layers`, must not be `None`")  # noqa: E501

        self._layers = layers

    @property
    def timestamp(self):
        """Gets the timestamp of this PCB.  # noqa: E501


        :return: The timestamp of this PCB.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this PCB.


        :param timestamp: The timestamp of this PCB.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PCB):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PCB):
            return True

        return self.to_dict() != other.to_dict()
