# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class PCBLayer(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'thickness': 'str',
        'thickness_calc': 'float',
        'material': 'int',
        'material_color': 'str',
        'material_name': 'str',
        'fill_material': 'int',
        'fill_material_color': 'str',
        'fill_material_name': 'str',
        'ratio': 'float',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'name': 'name',
        'thickness': 'thickness',
        'thickness_calc': 'thickness_calc',
        'material': 'material',
        'material_color': 'material_color',
        'material_name': 'material_name',
        'fill_material': 'fill_material',
        'fill_material_color': 'fill_material_color',
        'fill_material_name': 'fill_material_name',
        'ratio': 'ratio',
        'timestamp': 'timestamp'
    }

    def __init__(self, name=None, thickness=None, thickness_calc=None, material=None, material_color=None, material_name=None, fill_material=None, fill_material_color=None, fill_material_name=None, ratio=None, timestamp=None, local_vars_configuration=None):  # noqa: E501
        """PCBLayer - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._thickness = None
        self._thickness_calc = None
        self._material = None
        self._material_color = None
        self._material_name = None
        self._fill_material = None
        self._fill_material_color = None
        self._fill_material_name = None
        self._ratio = None
        self._timestamp = None
        self.discriminator = None

        self.name = name
        self.thickness = thickness
        if thickness_calc is not None:
            self.thickness_calc = thickness_calc
        self.material = material
        if material_color is not None:
            self.material_color = material_color
        if material_name is not None:
            self.material_name = material_name
        self.fill_material = fill_material
        if fill_material_color is not None:
            self.fill_material_color = fill_material_color
        if fill_material_name is not None:
            self.fill_material_name = fill_material_name
        if ratio is not None:
            self.ratio = ratio
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def name(self):
        """Gets the name of this PCBLayer.  # noqa: E501


        :return: The name of this PCBLayer.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PCBLayer.


        :param name: The name of this PCBLayer.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def thickness(self):
        """Gets the thickness of this PCBLayer.  # noqa: E501


        :return: The thickness of this PCBLayer.  # noqa: E501
        :rtype: str
        """
        return self._thickness

    @thickness.setter
    def thickness(self, thickness):
        """Sets the thickness of this PCBLayer.


        :param thickness: The thickness of this PCBLayer.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and thickness is None:  # noqa: E501
            raise ValueError("Invalid value for `thickness`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and thickness is not None and len(thickness) < 1):
            raise ValueError("Invalid value for `thickness`, length must be greater than or equal to `1`")  # noqa: E501

        self._thickness = thickness

    @property
    def thickness_calc(self):
        """Gets the thickness_calc of this PCBLayer.  # noqa: E501


        :return: The thickness_calc of this PCBLayer.  # noqa: E501
        :rtype: float
        """
        return self._thickness_calc

    @thickness_calc.setter
    def thickness_calc(self, thickness_calc):
        """Sets the thickness_calc of this PCBLayer.


        :param thickness_calc: The thickness_calc of this PCBLayer.  # noqa: E501
        :type: float
        """

        self._thickness_calc = thickness_calc

    @property
    def material(self):
        """Gets the material of this PCBLayer.  # noqa: E501


        :return: The material of this PCBLayer.  # noqa: E501
        :rtype: int
        """
        return self._material

    @material.setter
    def material(self, material):
        """Sets the material of this PCBLayer.


        :param material: The material of this PCBLayer.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and material is None:  # noqa: E501
            raise ValueError("Invalid value for `material`, must not be `None`")  # noqa: E501

        self._material = material

    @property
    def material_color(self):
        """Gets the material_color of this PCBLayer.  # noqa: E501


        :return: The material_color of this PCBLayer.  # noqa: E501
        :rtype: str
        """
        return self._material_color

    @material_color.setter
    def material_color(self, material_color):
        """Sets the material_color of this PCBLayer.


        :param material_color: The material_color of this PCBLayer.  # noqa: E501
        :type: str
        """

        self._material_color = material_color

    @property
    def material_name(self):
        """Gets the material_name of this PCBLayer.  # noqa: E501


        :return: The material_name of this PCBLayer.  # noqa: E501
        :rtype: str
        """
        return self._material_name

    @material_name.setter
    def material_name(self, material_name):
        """Sets the material_name of this PCBLayer.


        :param material_name: The material_name of this PCBLayer.  # noqa: E501
        :type: str
        """

        self._material_name = material_name

    @property
    def fill_material(self):
        """Gets the fill_material of this PCBLayer.  # noqa: E501


        :return: The fill_material of this PCBLayer.  # noqa: E501
        :rtype: int
        """
        return self._fill_material

    @fill_material.setter
    def fill_material(self, fill_material):
        """Sets the fill_material of this PCBLayer.


        :param fill_material: The fill_material of this PCBLayer.  # noqa: E501
        :type: int
        """

        self._fill_material = fill_material

    @property
    def fill_material_color(self):
        """Gets the fill_material_color of this PCBLayer.  # noqa: E501


        :return: The fill_material_color of this PCBLayer.  # noqa: E501
        :rtype: str
        """
        return self._fill_material_color

    @fill_material_color.setter
    def fill_material_color(self, fill_material_color):
        """Sets the fill_material_color of this PCBLayer.


        :param fill_material_color: The fill_material_color of this PCBLayer.  # noqa: E501
        :type: str
        """

        self._fill_material_color = fill_material_color

    @property
    def fill_material_name(self):
        """Gets the fill_material_name of this PCBLayer.  # noqa: E501


        :return: The fill_material_name of this PCBLayer.  # noqa: E501
        :rtype: str
        """
        return self._fill_material_name

    @fill_material_name.setter
    def fill_material_name(self, fill_material_name):
        """Sets the fill_material_name of this PCBLayer.


        :param fill_material_name: The fill_material_name of this PCBLayer.  # noqa: E501
        :type: str
        """

        self._fill_material_name = fill_material_name

    @property
    def ratio(self):
        """Gets the ratio of this PCBLayer.  # noqa: E501


        :return: The ratio of this PCBLayer.  # noqa: E501
        :rtype: float
        """
        return self._ratio

    @ratio.setter
    def ratio(self, ratio):
        """Sets the ratio of this PCBLayer.


        :param ratio: The ratio of this PCBLayer.  # noqa: E501
        :type: float
        """
        if (self.local_vars_configuration.client_side_validation and
                ratio is not None and ratio > 1E+2):  # noqa: E501
            raise ValueError("Invalid value for `ratio`, must be a value less than or equal to `1E+2`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                ratio is not None and ratio < 0):  # noqa: E501
            raise ValueError("Invalid value for `ratio`, must be a value greater than or equal to `0`")  # noqa: E501

        self._ratio = ratio

    @property
    def timestamp(self):
        """Gets the timestamp of this PCBLayer.  # noqa: E501


        :return: The timestamp of this PCBLayer.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this PCBLayer.


        :param timestamp: The timestamp of this PCBLayer.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PCBLayer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PCBLayer):
            return True

        return self.to_dict() != other.to_dict()
