# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class Plane(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'type': 'str',
        'plane': 'str',
        'coordinate': 'str',
        'visible': 'bool',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'plane': 'plane',
        'coordinate': 'coordinate',
        'visible': 'visible',
        'timestamp': 'timestamp'
    }

    def __init__(self, id=None, name=None, type=None, plane=None, coordinate=None, visible=None, timestamp=None, local_vars_configuration=None):  # noqa: E501
        """Plane - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._type = None
        self._plane = None
        self._coordinate = None
        self._visible = None
        self._timestamp = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        if type is not None:
            self.type = type
        self.plane = plane
        self.coordinate = coordinate
        if visible is not None:
            self.visible = visible
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def id(self):
        """Gets the id of this Plane.  # noqa: E501


        :return: The id of this Plane.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Plane.


        :param id: The id of this Plane.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Plane.  # noqa: E501


        :return: The name of this Plane.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Plane.


        :param name: The name of this Plane.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this Plane.  # noqa: E501


        :return: The type of this Plane.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Plane.


        :param type: The type of this Plane.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def plane(self):
        """Gets the plane of this Plane.  # noqa: E501


        :return: The plane of this Plane.  # noqa: E501
        :rtype: str
        """
        return self._plane

    @plane.setter
    def plane(self, plane):
        """Sets the plane of this Plane.


        :param plane: The plane of this Plane.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and plane is None:  # noqa: E501
            raise ValueError("Invalid value for `plane`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                plane is not None and len(plane) < 1):
            raise ValueError("Invalid value for `plane`, length must be greater than or equal to `1`")  # noqa: E501

        self._plane = plane

    @property
    def coordinate(self):
        """Gets the coordinate of this Plane.  # noqa: E501


        :return: The coordinate of this Plane.  # noqa: E501
        :rtype: str
        """
        return self._coordinate

    @coordinate.setter
    def coordinate(self, coordinate):
        """Sets the coordinate of this Plane.


        :param coordinate: The coordinate of this Plane.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and coordinate is None:  # noqa: E501
            raise ValueError("Invalid value for `coordinate`, must not be `None`")  # noqa: E501

        self._coordinate = coordinate

    @property
    def visible(self):
        """Gets the visible of this Plane.  # noqa: E501


        :return: The visible of this Plane.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this Plane.


        :param visible: The visible of this Plane.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    @property
    def timestamp(self):
        """Gets the timestamp of this Plane.  # noqa: E501


        :return: The timestamp of this Plane.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Plane.


        :param timestamp: The timestamp of this Plane.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Plane):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Plane):
            return True

        return self.to_dict() != other.to_dict()
