# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class ProjectTask(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'timestamp': 'datetime',
        'status': 'str',
        'user_name': 'str',
        'project': 'int',
        'project_name': 'str',
        'license': 'str',
        'instance': 'str'
    }

    attribute_map = {
        'id': 'id',
        'timestamp': 'timestamp',
        'status': 'status',
        'user_name': 'user_name',
        'project': 'project',
        'project_name': 'project_name',
        'license': 'license',
        'instance': 'instance'
    }

    def __init__(self, id=None, timestamp=None, status=None, user_name=None, project=None, project_name=None, license=None, instance=None, local_vars_configuration=None):  # noqa: E501
        """ProjectTask - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._timestamp = None
        self._status = None
        self._user_name = None
        self._project = None
        self._project_name = None
        self._license = None
        self._instance = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if timestamp is not None:
            self.timestamp = timestamp
        if status is not None:
            self.status = status
        if user_name is not None:
            self.user_name = user_name
        self.project = project
        if project_name is not None:
            self.project_name = project_name
        if license is not None:
            self.license = license
        self.instance = instance

    @property
    def id(self):
        """Gets the id of this ProjectTask.  # noqa: E501


        :return: The id of this ProjectTask.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProjectTask.


        :param id: The id of this ProjectTask.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def timestamp(self):
        """Gets the timestamp of this ProjectTask.  # noqa: E501


        :return: The timestamp of this ProjectTask.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ProjectTask.


        :param timestamp: The timestamp of this ProjectTask.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    @property
    def status(self):
        """Gets the status of this ProjectTask.  # noqa: E501


        :return: The status of this ProjectTask.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ProjectTask.


        :param status: The status of this ProjectTask.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def user_name(self):
        """Gets the user_name of this ProjectTask.  # noqa: E501


        :return: The user_name of this ProjectTask.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this ProjectTask.


        :param user_name: The user_name of this ProjectTask.  # noqa: E501
        :type: str
        """

        self._user_name = user_name

    @property
    def project(self):
        """Gets the project of this ProjectTask.  # noqa: E501


        :return: The project of this ProjectTask.  # noqa: E501
        :rtype: int
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this ProjectTask.


        :param project: The project of this ProjectTask.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and project is None:  # noqa: E501
            raise ValueError("Invalid value for `project`, must not be `None`")  # noqa: E501

        self._project = project

    @property
    def project_name(self):
        """Gets the project_name of this ProjectTask.  # noqa: E501


        :return: The project_name of this ProjectTask.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this ProjectTask.


        :param project_name: The project_name of this ProjectTask.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def license(self):
        """Gets the license of this ProjectTask.  # noqa: E501


        :return: The license of this ProjectTask.  # noqa: E501
        :rtype: str
        """
        return self._license

    @license.setter
    def license(self, license):
        """Sets the license of this ProjectTask.


        :param license: The license of this ProjectTask.  # noqa: E501
        :type: str
        """

        self._license = license

    @property
    def instance(self):
        """Gets the instance of this ProjectTask.  # noqa: E501


        :return: The instance of this ProjectTask.  # noqa: E501
        :rtype: str
        """
        return self._instance

    @instance.setter
    def instance(self, instance):
        """Sets the instance of this ProjectTask.


        :param instance: The instance of this ProjectTask.  # noqa: E501
        :type: str
        """

        self._instance = instance

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectTask):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectTask):
            return True

        return self.to_dict() != other.to_dict()
