# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class Project(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'created': 'datetime',
        'folder': 'int',
        'last_modified': 'datetime',
        'world': 'World',
        'thumbnail': 'str',
        'owner': 'bool',
        'edit': 'bool',
        'view': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'created': 'created',
        'folder': 'folder',
        'last_modified': 'last_modified',
        'world': 'world',
        'thumbnail': 'thumbnail',
        'owner': 'owner',
        'edit': 'edit',
        'view': 'view'
    }

    def __init__(self, id=None, name=None, created=None, folder=None, last_modified=None, world=None, thumbnail=None, owner=None, edit=None, view=None, local_vars_configuration=None):  # noqa: E501
        """Project - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._created = None
        self._folder = None
        self._last_modified = None
        self._world = None
        self._thumbnail = None
        self._owner = None
        self._edit = None
        self._view = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        if created is not None:
            self.created = created
        self.folder = folder
        if last_modified is not None:
            self.last_modified = last_modified
        self.world = world
        if thumbnail is not None:
            self.thumbnail = thumbnail
        if owner is not None:
            self.owner = owner
        if edit is not None:
            self.edit = edit
        if view is not None:
            self.view = view

    @property
    def id(self):
        """Gets the id of this Project.  # noqa: E501


        :return: The id of this Project.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Project.


        :param id: The id of this Project.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Project.  # noqa: E501


        :return: The name of this Project.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Project.


        :param name: The name of this Project.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def created(self):
        """Gets the created of this Project.  # noqa: E501


        :return: The created of this Project.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Project.


        :param created: The created of this Project.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def folder(self):
        """Gets the folder of this Project.  # noqa: E501


        :return: The folder of this Project.  # noqa: E501
        :rtype: int
        """
        return self._folder

    @folder.setter
    def folder(self, folder):
        """Sets the folder of this Project.


        :param folder: The folder of this Project.  # noqa: E501
        :type: int
        """

        self._folder = folder

    @property
    def last_modified(self):
        """Gets the last_modified of this Project.  # noqa: E501


        :return: The last_modified of this Project.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """Sets the last_modified of this Project.


        :param last_modified: The last_modified of this Project.  # noqa: E501
        :type: datetime
        """

        self._last_modified = last_modified

    @property
    def world(self):
        """Gets the world of this Project.  # noqa: E501


        :return: The world of this Project.  # noqa: E501
        :rtype: World
        """
        return self._world

    @world.setter
    def world(self, world):
        """Sets the world of this Project.


        :param world: The world of this Project.  # noqa: E501
        :type: World
        """
        if self.local_vars_configuration.client_side_validation and world is None:  # noqa: E501
            raise ValueError("Invalid value for `world`, must not be `None`")  # noqa: E501

        self._world = world

    @property
    def thumbnail(self):
        """Gets the thumbnail of this Project.  # noqa: E501


        :return: The thumbnail of this Project.  # noqa: E501
        :rtype: str
        """
        return self._thumbnail

    @thumbnail.setter
    def thumbnail(self, thumbnail):
        """Sets the thumbnail of this Project.


        :param thumbnail: The thumbnail of this Project.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                thumbnail is not None and len(thumbnail) < 1):
            raise ValueError("Invalid value for `thumbnail`, length must be greater than or equal to `1`")  # noqa: E501

        self._thumbnail = thumbnail

    @property
    def owner(self):
        """Gets the owner of this Project.  # noqa: E501


        :return: The owner of this Project.  # noqa: E501
        :rtype: bool
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Project.


        :param owner: The owner of this Project.  # noqa: E501
        :type: bool
        """

        self._owner = owner

    @property
    def edit(self):
        """Gets the edit of this Project.  # noqa: E501


        :return: The edit of this Project.  # noqa: E501
        :rtype: bool
        """
        return self._edit

    @edit.setter
    def edit(self, edit):
        """Sets the edit of this Project.


        :param edit: The edit of this Project.  # noqa: E501
        :type: bool
        """

        self._edit = edit

    @property
    def view(self):
        """Gets the view of this Project.  # noqa: E501


        :return: The view of this Project.  # noqa: E501
        :rtype: bool
        """
        return self._view

    @view.setter
    def view(self, view):
        """Sets the view of this Project.


        :param view: The view of this Project.  # noqa: E501
        :type: bool
        """

        self._view = view

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Project):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Project):
            return True

        return self.to_dict() != other.to_dict()
