# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class ProjectMaterial(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'library_name': 'str',
        'color': 'str',
        'anisotropic': 'bool',
        'conductivity': 'str',
        'conductivity_y': 'str',
        'conductivity_z': 'str',
        'conductivity_calc': 'float',
        'conductivity_y_calc': 'float',
        'conductivity_z_calc': 'float',
        'density': 'float',
        'specific_heat': 'float',
        'material': 'int',
        'source_material': 'Material',
        'used': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'library_name': 'library_name',
        'color': 'color',
        'anisotropic': 'anisotropic',
        'conductivity': 'conductivity',
        'conductivity_y': 'conductivity_y',
        'conductivity_z': 'conductivity_z',
        'conductivity_calc': 'conductivity_calc',
        'conductivity_y_calc': 'conductivity_y_calc',
        'conductivity_z_calc': 'conductivity_z_calc',
        'density': 'density',
        'specific_heat': 'specific_heat',
        'material': 'material',
        'source_material': 'source_material',
        'used': 'used'
    }

    def __init__(self, id=None, name=None, library_name=None, color=None, anisotropic=None, conductivity=None, conductivity_y=None, conductivity_z=None, conductivity_calc=None, conductivity_y_calc=None, conductivity_z_calc=None, density=None, specific_heat=None, material=None, source_material=None, used=None, local_vars_configuration=None):  # noqa: E501
        """ProjectMaterial - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._library_name = None
        self._color = None
        self._anisotropic = None
        self._conductivity = None
        self._conductivity_y = None
        self._conductivity_z = None
        self._conductivity_calc = None
        self._conductivity_y_calc = None
        self._conductivity_z_calc = None
        self._density = None
        self._specific_heat = None
        self._material = None
        self._source_material = None
        self._used = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.library_name = library_name
        self.color = color
        if anisotropic is not None:
            self.anisotropic = anisotropic
        self.conductivity = conductivity
        self.conductivity_y = conductivity_y
        self.conductivity_z = conductivity_z
        if conductivity_calc is not None:
            self.conductivity_calc = conductivity_calc
        self.conductivity_y_calc = conductivity_y_calc
        self.conductivity_z_calc = conductivity_z_calc
        self.density = density
        self.specific_heat = specific_heat
        self.material = material
        if source_material is not None:
            self.source_material = source_material
        if used is not None:
            self.used = used

    @property
    def id(self):
        """Gets the id of this ProjectMaterial.  # noqa: E501


        :return: The id of this ProjectMaterial.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProjectMaterial.


        :param id: The id of this ProjectMaterial.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ProjectMaterial.  # noqa: E501


        :return: The name of this ProjectMaterial.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectMaterial.


        :param name: The name of this ProjectMaterial.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def library_name(self):
        """Gets the library_name of this ProjectMaterial.  # noqa: E501


        :return: The library_name of this ProjectMaterial.  # noqa: E501
        :rtype: str
        """
        return self._library_name

    @library_name.setter
    def library_name(self, library_name):
        """Sets the library_name of this ProjectMaterial.


        :param library_name: The library_name of this ProjectMaterial.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                library_name is not None and len(library_name) < 1):
            raise ValueError("Invalid value for `library_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._library_name = library_name

    @property
    def color(self):
        """Gets the color of this ProjectMaterial.  # noqa: E501


        :return: The color of this ProjectMaterial.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this ProjectMaterial.


        :param color: The color of this ProjectMaterial.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and color is None:  # noqa: E501
            raise ValueError("Invalid value for `color`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                color is not None and len(color) < 1):
            raise ValueError("Invalid value for `color`, length must be greater than or equal to `1`")  # noqa: E501

        self._color = color

    @property
    def anisotropic(self):
        """Gets the anisotropic of this ProjectMaterial.  # noqa: E501


        :return: The anisotropic of this ProjectMaterial.  # noqa: E501
        :rtype: bool
        """
        return self._anisotropic

    @anisotropic.setter
    def anisotropic(self, anisotropic):
        """Sets the anisotropic of this ProjectMaterial.


        :param anisotropic: The anisotropic of this ProjectMaterial.  # noqa: E501
        :type: bool
        """

        self._anisotropic = anisotropic

    @property
    def conductivity(self):
        """Gets the conductivity of this ProjectMaterial.  # noqa: E501


        :return: The conductivity of this ProjectMaterial.  # noqa: E501
        :rtype: str
        """
        return self._conductivity

    @conductivity.setter
    def conductivity(self, conductivity):
        """Sets the conductivity of this ProjectMaterial.


        :param conductivity: The conductivity of this ProjectMaterial.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and conductivity is None:  # noqa: E501
            raise ValueError("Invalid value for `conductivity`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                conductivity is not None and len(conductivity) < 1):
            raise ValueError("Invalid value for `conductivity`, length must be greater than or equal to `1`")  # noqa: E501

        self._conductivity = conductivity

    @property
    def conductivity_y(self):
        """Gets the conductivity_y of this ProjectMaterial.  # noqa: E501


        :return: The conductivity_y of this ProjectMaterial.  # noqa: E501
        :rtype: str
        """
        return self._conductivity_y

    @conductivity_y.setter
    def conductivity_y(self, conductivity_y):
        """Sets the conductivity_y of this ProjectMaterial.


        :param conductivity_y: The conductivity_y of this ProjectMaterial.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                conductivity_y is not None and len(conductivity_y) < 1):
            raise ValueError("Invalid value for `conductivity_y`, length must be greater than or equal to `1`")  # noqa: E501

        self._conductivity_y = conductivity_y

    @property
    def conductivity_z(self):
        """Gets the conductivity_z of this ProjectMaterial.  # noqa: E501


        :return: The conductivity_z of this ProjectMaterial.  # noqa: E501
        :rtype: str
        """
        return self._conductivity_z

    @conductivity_z.setter
    def conductivity_z(self, conductivity_z):
        """Sets the conductivity_z of this ProjectMaterial.


        :param conductivity_z: The conductivity_z of this ProjectMaterial.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                conductivity_z is not None and len(conductivity_z) < 1):
            raise ValueError("Invalid value for `conductivity_z`, length must be greater than or equal to `1`")  # noqa: E501

        self._conductivity_z = conductivity_z

    @property
    def conductivity_calc(self):
        """Gets the conductivity_calc of this ProjectMaterial.  # noqa: E501


        :return: The conductivity_calc of this ProjectMaterial.  # noqa: E501
        :rtype: float
        """
        return self._conductivity_calc

    @conductivity_calc.setter
    def conductivity_calc(self, conductivity_calc):
        """Sets the conductivity_calc of this ProjectMaterial.


        :param conductivity_calc: The conductivity_calc of this ProjectMaterial.  # noqa: E501
        :type: float
        """

        self._conductivity_calc = conductivity_calc

    @property
    def conductivity_y_calc(self):
        """Gets the conductivity_y_calc of this ProjectMaterial.  # noqa: E501


        :return: The conductivity_y_calc of this ProjectMaterial.  # noqa: E501
        :rtype: float
        """
        return self._conductivity_y_calc

    @conductivity_y_calc.setter
    def conductivity_y_calc(self, conductivity_y_calc):
        """Sets the conductivity_y_calc of this ProjectMaterial.


        :param conductivity_y_calc: The conductivity_y_calc of this ProjectMaterial.  # noqa: E501
        :type: float
        """

        self._conductivity_y_calc = conductivity_y_calc

    @property
    def conductivity_z_calc(self):
        """Gets the conductivity_z_calc of this ProjectMaterial.  # noqa: E501


        :return: The conductivity_z_calc of this ProjectMaterial.  # noqa: E501
        :rtype: float
        """
        return self._conductivity_z_calc

    @conductivity_z_calc.setter
    def conductivity_z_calc(self, conductivity_z_calc):
        """Sets the conductivity_z_calc of this ProjectMaterial.


        :param conductivity_z_calc: The conductivity_z_calc of this ProjectMaterial.  # noqa: E501
        :type: float
        """

        self._conductivity_z_calc = conductivity_z_calc

    @property
    def density(self):
        """Gets the density of this ProjectMaterial.  # noqa: E501


        :return: The density of this ProjectMaterial.  # noqa: E501
        :rtype: float
        """
        return self._density

    @density.setter
    def density(self, density):
        """Sets the density of this ProjectMaterial.


        :param density: The density of this ProjectMaterial.  # noqa: E501
        :type: float
        """

        self._density = density

    @property
    def specific_heat(self):
        """Gets the specific_heat of this ProjectMaterial.  # noqa: E501


        :return: The specific_heat of this ProjectMaterial.  # noqa: E501
        :rtype: float
        """
        return self._specific_heat

    @specific_heat.setter
    def specific_heat(self, specific_heat):
        """Sets the specific_heat of this ProjectMaterial.


        :param specific_heat: The specific_heat of this ProjectMaterial.  # noqa: E501
        :type: float
        """

        self._specific_heat = specific_heat

    @property
    def material(self):
        """Gets the material of this ProjectMaterial.  # noqa: E501


        :return: The material of this ProjectMaterial.  # noqa: E501
        :rtype: int
        """
        return self._material

    @material.setter
    def material(self, material):
        """Sets the material of this ProjectMaterial.


        :param material: The material of this ProjectMaterial.  # noqa: E501
        :type: int
        """

        self._material = material

    @property
    def source_material(self):
        """Gets the source_material of this ProjectMaterial.  # noqa: E501


        :return: The source_material of this ProjectMaterial.  # noqa: E501
        :rtype: Material
        """
        return self._source_material

    @source_material.setter
    def source_material(self, source_material):
        """Sets the source_material of this ProjectMaterial.


        :param source_material: The source_material of this ProjectMaterial.  # noqa: E501
        :type: Material
        """

        self._source_material = source_material

    @property
    def used(self):
        """Gets the used of this ProjectMaterial.  # noqa: E501


        :return: The used of this ProjectMaterial.  # noqa: E501
        :rtype: bool
        """
        return self._used

    @used.setter
    def used(self, used):
        """Sets the used of this ProjectMaterial.


        :param used: The used of this ProjectMaterial.  # noqa: E501
        :type: bool
        """

        self._used = used

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectMaterial):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectMaterial):
            return True

        return self.to_dict() != other.to_dict()
