# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class ScenarioParameter(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'parameter': 'int',
        'parameter_name': 'str',
        'parameter_description': 'str',
        'default': 'bool',
        'default_value': 'str',
        'values': 'list[float]',
        'random': 'RandomValues',
        'normal_dist': 'NormalDist'
    }

    attribute_map = {
        'id': 'id',
        'parameter': 'parameter',
        'parameter_name': 'parameter_name',
        'parameter_description': 'parameter_description',
        'default': 'default',
        'default_value': 'default_value',
        'values': 'values',
        'random': 'random',
        'normal_dist': 'normal_dist'
    }

    def __init__(self, id=None, parameter=None, parameter_name=None, parameter_description=None, default=None, default_value=None, values=None, random=None, normal_dist=None, local_vars_configuration=None):  # noqa: E501
        """ScenarioParameter - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._parameter = None
        self._parameter_name = None
        self._parameter_description = None
        self._default = None
        self._default_value = None
        self._values = None
        self._random = None
        self._normal_dist = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.parameter = parameter
        if parameter_name is not None:
            self.parameter_name = parameter_name
        if parameter_description is not None:
            self.parameter_description = parameter_description
        self.default = default
        if default_value is not None:
            self.default_value = default_value
        self.values = values
        self.random = random
        self.normal_dist = normal_dist

    @property
    def id(self):
        """Gets the id of this ScenarioParameter.  # noqa: E501


        :return: The id of this ScenarioParameter.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ScenarioParameter.


        :param id: The id of this ScenarioParameter.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def parameter(self):
        """Gets the parameter of this ScenarioParameter.  # noqa: E501


        :return: The parameter of this ScenarioParameter.  # noqa: E501
        :rtype: int
        """
        return self._parameter

    @parameter.setter
    def parameter(self, parameter):
        """Sets the parameter of this ScenarioParameter.


        :param parameter: The parameter of this ScenarioParameter.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and parameter is None:  # noqa: E501
            raise ValueError("Invalid value for `parameter`, must not be `None`")  # noqa: E501

        self._parameter = parameter

    @property
    def parameter_name(self):
        """Gets the parameter_name of this ScenarioParameter.  # noqa: E501


        :return: The parameter_name of this ScenarioParameter.  # noqa: E501
        :rtype: str
        """
        return self._parameter_name

    @parameter_name.setter
    def parameter_name(self, parameter_name):
        """Sets the parameter_name of this ScenarioParameter.


        :param parameter_name: The parameter_name of this ScenarioParameter.  # noqa: E501
        :type: str
        """

        self._parameter_name = parameter_name

    @property
    def parameter_description(self):
        """Gets the parameter_description of this ScenarioParameter.  # noqa: E501


        :return: The parameter_description of this ScenarioParameter.  # noqa: E501
        :rtype: str
        """
        return self._parameter_description

    @parameter_description.setter
    def parameter_description(self, parameter_description):
        """Sets the parameter_description of this ScenarioParameter.


        :param parameter_description: The parameter_description of this ScenarioParameter.  # noqa: E501
        :type: str
        """

        self._parameter_description = parameter_description

    @property
    def default(self):
        """Gets the default of this ScenarioParameter.  # noqa: E501


        :return: The default of this ScenarioParameter.  # noqa: E501
        :rtype: bool
        """
        return self._default

    @default.setter
    def default(self, default):
        """Sets the default of this ScenarioParameter.


        :param default: The default of this ScenarioParameter.  # noqa: E501
        :type: bool
        """

        self._default = default

    @property
    def default_value(self):
        """Gets the default_value of this ScenarioParameter.  # noqa: E501


        :return: The default_value of this ScenarioParameter.  # noqa: E501
        :rtype: str
        """
        return self._default_value

    @default_value.setter
    def default_value(self, default_value):
        """Sets the default_value of this ScenarioParameter.


        :param default_value: The default_value of this ScenarioParameter.  # noqa: E501
        :type: str
        """

        self._default_value = default_value

    @property
    def values(self):
        """Gets the values of this ScenarioParameter.  # noqa: E501


        :return: The values of this ScenarioParameter.  # noqa: E501
        :rtype: list[float]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this ScenarioParameter.


        :param values: The values of this ScenarioParameter.  # noqa: E501
        :type: list[float]
        """

        self._values = values

    @property
    def random(self):
        """Gets the random of this ScenarioParameter.  # noqa: E501


        :return: The random of this ScenarioParameter.  # noqa: E501
        :rtype: RandomValues
        """
        return self._random

    @random.setter
    def random(self, random):
        """Sets the random of this ScenarioParameter.


        :param random: The random of this ScenarioParameter.  # noqa: E501
        :type: RandomValues
        """

        self._random = random

    @property
    def normal_dist(self):
        """Gets the normal_dist of this ScenarioParameter.  # noqa: E501


        :return: The normal_dist of this ScenarioParameter.  # noqa: E501
        :rtype: NormalDist
        """
        return self._normal_dist

    @normal_dist.setter
    def normal_dist(self, normal_dist):
        """Sets the normal_dist of this ScenarioParameter.


        :param normal_dist: The normal_dist of this ScenarioParameter.  # noqa: E501
        :type: NormalDist
        """

        self._normal_dist = normal_dist

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScenarioParameter):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ScenarioParameter):
            return True

        return self.to_dict() != other.to_dict()
