# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class SimpleAssembly(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'index': 'int',
        'type': 'str',
        'leaf': 'bool',
        'parent': 'int',
        'visible': 'bool',
        'collapsed': 'bool',
        'active': 'bool',
        'timestamp': 'datetime',
        'lumped': 'bool',
        'hc': 'str',
        'is_array': 'bool',
        'xcount': 'str',
        'ycount': 'str',
        'zcount': 'str',
        'xpitch': 'str',
        'ypitch': 'str',
        'zpitch': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'index': 'index',
        'type': 'type',
        'leaf': 'leaf',
        'parent': 'parent',
        'visible': 'visible',
        'collapsed': 'collapsed',
        'active': 'active',
        'timestamp': 'timestamp',
        'lumped': 'lumped',
        'hc': 'hc',
        'is_array': 'is_array',
        'xcount': 'xcount',
        'ycount': 'ycount',
        'zcount': 'zcount',
        'xpitch': 'xpitch',
        'ypitch': 'ypitch',
        'zpitch': 'zpitch'
    }

    def __init__(self, id=None, name=None, index=None, type=None, leaf=None, parent=None, visible=None, collapsed=None, active=None, timestamp=None, lumped=None, hc=None, is_array=None, xcount=None, ycount=None, zcount=None, xpitch=None, ypitch=None, zpitch=None, local_vars_configuration=None):  # noqa: E501
        """SimpleAssembly - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._index = None
        self._type = None
        self._leaf = None
        self._parent = None
        self._visible = None
        self._collapsed = None
        self._active = None
        self._timestamp = None
        self._lumped = None
        self._hc = None
        self._is_array = None
        self._xcount = None
        self._ycount = None
        self._zcount = None
        self._xpitch = None
        self._ypitch = None
        self._zpitch = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.index = index
        if type is not None:
            self.type = type
        if leaf is not None:
            self.leaf = leaf
        self.parent = parent
        if visible is not None:
            self.visible = visible
        if collapsed is not None:
            self.collapsed = collapsed
        if active is not None:
            self.active = active
        if timestamp is not None:
            self.timestamp = timestamp
        if lumped is not None:
            self.lumped = lumped
        self.hc = hc
        if is_array is not None:
            self.is_array = is_array
        if xcount is not None:
            self.xcount = xcount
        if ycount is not None:
            self.ycount = ycount
        if zcount is not None:
            self.zcount = zcount
        if xpitch is not None:
            self.xpitch = xpitch
        if ypitch is not None:
            self.ypitch = ypitch
        if zpitch is not None:
            self.zpitch = zpitch

    @property
    def id(self):
        """Gets the id of this SimpleAssembly.  # noqa: E501


        :return: The id of this SimpleAssembly.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SimpleAssembly.


        :param id: The id of this SimpleAssembly.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SimpleAssembly.  # noqa: E501


        :return: The name of this SimpleAssembly.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SimpleAssembly.


        :param name: The name of this SimpleAssembly.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def index(self):
        """Gets the index of this SimpleAssembly.  # noqa: E501


        :return: The index of this SimpleAssembly.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this SimpleAssembly.


        :param index: The index of this SimpleAssembly.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and index is None:  # noqa: E501
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index is not None and index > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `index`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index is not None and index < 0):  # noqa: E501
            raise ValueError("Invalid value for `index`, must be a value greater than or equal to `0`")  # noqa: E501

        self._index = index

    @property
    def type(self):
        """Gets the type of this SimpleAssembly.  # noqa: E501


        :return: The type of this SimpleAssembly.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SimpleAssembly.


        :param type: The type of this SimpleAssembly.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def leaf(self):
        """Gets the leaf of this SimpleAssembly.  # noqa: E501


        :return: The leaf of this SimpleAssembly.  # noqa: E501
        :rtype: bool
        """
        return self._leaf

    @leaf.setter
    def leaf(self, leaf):
        """Sets the leaf of this SimpleAssembly.


        :param leaf: The leaf of this SimpleAssembly.  # noqa: E501
        :type: bool
        """

        self._leaf = leaf

    @property
    def parent(self):
        """Gets the parent of this SimpleAssembly.  # noqa: E501


        :return: The parent of this SimpleAssembly.  # noqa: E501
        :rtype: int
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this SimpleAssembly.


        :param parent: The parent of this SimpleAssembly.  # noqa: E501
        :type: int
        """

        self._parent = parent

    @property
    def visible(self):
        """Gets the visible of this SimpleAssembly.  # noqa: E501


        :return: The visible of this SimpleAssembly.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this SimpleAssembly.


        :param visible: The visible of this SimpleAssembly.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    @property
    def collapsed(self):
        """Gets the collapsed of this SimpleAssembly.  # noqa: E501


        :return: The collapsed of this SimpleAssembly.  # noqa: E501
        :rtype: bool
        """
        return self._collapsed

    @collapsed.setter
    def collapsed(self, collapsed):
        """Sets the collapsed of this SimpleAssembly.


        :param collapsed: The collapsed of this SimpleAssembly.  # noqa: E501
        :type: bool
        """

        self._collapsed = collapsed

    @property
    def active(self):
        """Gets the active of this SimpleAssembly.  # noqa: E501


        :return: The active of this SimpleAssembly.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this SimpleAssembly.


        :param active: The active of this SimpleAssembly.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def timestamp(self):
        """Gets the timestamp of this SimpleAssembly.  # noqa: E501


        :return: The timestamp of this SimpleAssembly.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this SimpleAssembly.


        :param timestamp: The timestamp of this SimpleAssembly.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    @property
    def lumped(self):
        """Gets the lumped of this SimpleAssembly.  # noqa: E501


        :return: The lumped of this SimpleAssembly.  # noqa: E501
        :rtype: bool
        """
        return self._lumped

    @lumped.setter
    def lumped(self, lumped):
        """Sets the lumped of this SimpleAssembly.


        :param lumped: The lumped of this SimpleAssembly.  # noqa: E501
        :type: bool
        """

        self._lumped = lumped

    @property
    def hc(self):
        """Gets the hc of this SimpleAssembly.  # noqa: E501


        :return: The hc of this SimpleAssembly.  # noqa: E501
        :rtype: str
        """
        return self._hc

    @hc.setter
    def hc(self, hc):
        """Sets the hc of this SimpleAssembly.


        :param hc: The hc of this SimpleAssembly.  # noqa: E501
        :type: str
        """

        self._hc = hc

    @property
    def is_array(self):
        """Gets the is_array of this SimpleAssembly.  # noqa: E501


        :return: The is_array of this SimpleAssembly.  # noqa: E501
        :rtype: bool
        """
        return self._is_array

    @is_array.setter
    def is_array(self, is_array):
        """Sets the is_array of this SimpleAssembly.


        :param is_array: The is_array of this SimpleAssembly.  # noqa: E501
        :type: bool
        """

        self._is_array = is_array

    @property
    def xcount(self):
        """Gets the xcount of this SimpleAssembly.  # noqa: E501


        :return: The xcount of this SimpleAssembly.  # noqa: E501
        :rtype: str
        """
        return self._xcount

    @xcount.setter
    def xcount(self, xcount):
        """Sets the xcount of this SimpleAssembly.


        :param xcount: The xcount of this SimpleAssembly.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                xcount is not None and len(xcount) < 1):
            raise ValueError("Invalid value for `xcount`, length must be greater than or equal to `1`")  # noqa: E501

        self._xcount = xcount

    @property
    def ycount(self):
        """Gets the ycount of this SimpleAssembly.  # noqa: E501


        :return: The ycount of this SimpleAssembly.  # noqa: E501
        :rtype: str
        """
        return self._ycount

    @ycount.setter
    def ycount(self, ycount):
        """Sets the ycount of this SimpleAssembly.


        :param ycount: The ycount of this SimpleAssembly.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                ycount is not None and len(ycount) < 1):
            raise ValueError("Invalid value for `ycount`, length must be greater than or equal to `1`")  # noqa: E501

        self._ycount = ycount

    @property
    def zcount(self):
        """Gets the zcount of this SimpleAssembly.  # noqa: E501


        :return: The zcount of this SimpleAssembly.  # noqa: E501
        :rtype: str
        """
        return self._zcount

    @zcount.setter
    def zcount(self, zcount):
        """Sets the zcount of this SimpleAssembly.


        :param zcount: The zcount of this SimpleAssembly.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                zcount is not None and len(zcount) < 1):
            raise ValueError("Invalid value for `zcount`, length must be greater than or equal to `1`")  # noqa: E501

        self._zcount = zcount

    @property
    def xpitch(self):
        """Gets the xpitch of this SimpleAssembly.  # noqa: E501


        :return: The xpitch of this SimpleAssembly.  # noqa: E501
        :rtype: str
        """
        return self._xpitch

    @xpitch.setter
    def xpitch(self, xpitch):
        """Sets the xpitch of this SimpleAssembly.


        :param xpitch: The xpitch of this SimpleAssembly.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                xpitch is not None and len(xpitch) < 1):
            raise ValueError("Invalid value for `xpitch`, length must be greater than or equal to `1`")  # noqa: E501

        self._xpitch = xpitch

    @property
    def ypitch(self):
        """Gets the ypitch of this SimpleAssembly.  # noqa: E501


        :return: The ypitch of this SimpleAssembly.  # noqa: E501
        :rtype: str
        """
        return self._ypitch

    @ypitch.setter
    def ypitch(self, ypitch):
        """Sets the ypitch of this SimpleAssembly.


        :param ypitch: The ypitch of this SimpleAssembly.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                ypitch is not None and len(ypitch) < 1):
            raise ValueError("Invalid value for `ypitch`, length must be greater than or equal to `1`")  # noqa: E501

        self._ypitch = ypitch

    @property
    def zpitch(self):
        """Gets the zpitch of this SimpleAssembly.  # noqa: E501


        :return: The zpitch of this SimpleAssembly.  # noqa: E501
        :rtype: str
        """
        return self._zpitch

    @zpitch.setter
    def zpitch(self, zpitch):
        """Sets the zpitch of this SimpleAssembly.


        :param zpitch: The zpitch of this SimpleAssembly.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                zpitch is not None and len(zpitch) < 1):
            raise ValueError("Invalid value for `zpitch`, length must be greater than or equal to `1`")  # noqa: E501

        self._zpitch = zpitch

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SimpleAssembly):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SimpleAssembly):
            return True

        return self.to_dict() != other.to_dict()
