# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class TransientSourcePower(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'time': 'float',
        'power': 'str',
        'power_calc': 'float'
    }

    attribute_map = {
        'id': 'id',
        'time': 'time',
        'power': 'power',
        'power_calc': 'power_calc'
    }

    def __init__(self, id=None, time=None, power=None, power_calc=None, local_vars_configuration=None):  # noqa: E501
        """TransientSourcePower - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._time = None
        self._power = None
        self._power_calc = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.time = time
        if power is not None:
            self.power = power
        if power_calc is not None:
            self.power_calc = power_calc

    @property
    def id(self):
        """Gets the id of this TransientSourcePower.  # noqa: E501


        :return: The id of this TransientSourcePower.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TransientSourcePower.


        :param id: The id of this TransientSourcePower.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def time(self):
        """Gets the time of this TransientSourcePower.  # noqa: E501


        :return: The time of this TransientSourcePower.  # noqa: E501
        :rtype: float
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this TransientSourcePower.


        :param time: The time of this TransientSourcePower.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and time is None:  # noqa: E501
            raise ValueError("Invalid value for `time`, must not be `None`")  # noqa: E501

        self._time = time

    @property
    def power(self):
        """Gets the power of this TransientSourcePower.  # noqa: E501


        :return: The power of this TransientSourcePower.  # noqa: E501
        :rtype: str
        """
        return self._power

    @power.setter
    def power(self, power):
        """Sets the power of this TransientSourcePower.


        :param power: The power of this TransientSourcePower.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                power is not None and len(power) < 1):
            raise ValueError("Invalid value for `power`, length must be greater than or equal to `1`")  # noqa: E501

        self._power = power

    @property
    def power_calc(self):
        """Gets the power_calc of this TransientSourcePower.  # noqa: E501


        :return: The power_calc of this TransientSourcePower.  # noqa: E501
        :rtype: float
        """
        return self._power_calc

    @power_calc.setter
    def power_calc(self, power_calc):
        """Sets the power_calc of this TransientSourcePower.


        :param power_calc: The power_calc of this TransientSourcePower.  # noqa: E501
        :type: float
        """

        self._power_calc = power_calc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransientSourcePower):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TransientSourcePower):
            return True

        return self.to_dict() != other.to_dict()
