# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class UserLicenseInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'user': 'UserLicenseInfoUser',
        'licenses': 'list[UserLicenseInfoLicenses]'
    }

    attribute_map = {
        'user': 'user',
        'licenses': 'licenses'
    }

    def __init__(self, user=None, licenses=None, local_vars_configuration=None):  # noqa: E501
        """UserLicenseInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._user = None
        self._licenses = None
        self.discriminator = None

        if user is not None:
            self.user = user
        if licenses is not None:
            self.licenses = licenses

    @property
    def user(self):
        """Gets the user of this UserLicenseInfo.  # noqa: E501


        :return: The user of this UserLicenseInfo.  # noqa: E501
        :rtype: UserLicenseInfoUser
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this UserLicenseInfo.


        :param user: The user of this UserLicenseInfo.  # noqa: E501
        :type: UserLicenseInfoUser
        """

        self._user = user

    @property
    def licenses(self):
        """Gets the licenses of this UserLicenseInfo.  # noqa: E501


        :return: The licenses of this UserLicenseInfo.  # noqa: E501
        :rtype: list[UserLicenseInfoLicenses]
        """
        return self._licenses

    @licenses.setter
    def licenses(self, licenses):
        """Sets the licenses of this UserLicenseInfo.


        :param licenses: The licenses of this UserLicenseInfo.  # noqa: E501
        :type: list[UserLicenseInfoLicenses]
        """

        self._licenses = licenses

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserLicenseInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserLicenseInfo):
            return True

        return self.to_dict() != other.to_dict()
