# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class UserLicenseInfoUser(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'email': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'thermal_token': 'str',
        'groups': 'list[str]'
    }

    attribute_map = {
        'email': 'email',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'thermal_token': 'thermal_token',
        'groups': 'groups'
    }

    def __init__(self, email=None, first_name=None, last_name=None, thermal_token=None, groups=None, local_vars_configuration=None):  # noqa: E501
        """UserLicenseInfoUser - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._email = None
        self._first_name = None
        self._last_name = None
        self._thermal_token = None
        self._groups = None
        self.discriminator = None

        if email is not None:
            self.email = email
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if thermal_token is not None:
            self.thermal_token = thermal_token
        if groups is not None:
            self.groups = groups

    @property
    def email(self):
        """Gets the email of this UserLicenseInfoUser.  # noqa: E501


        :return: The email of this UserLicenseInfoUser.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserLicenseInfoUser.


        :param email: The email of this UserLicenseInfoUser.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def first_name(self):
        """Gets the first_name of this UserLicenseInfoUser.  # noqa: E501


        :return: The first_name of this UserLicenseInfoUser.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UserLicenseInfoUser.


        :param first_name: The first_name of this UserLicenseInfoUser.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this UserLicenseInfoUser.  # noqa: E501


        :return: The last_name of this UserLicenseInfoUser.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this UserLicenseInfoUser.


        :param last_name: The last_name of this UserLicenseInfoUser.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def thermal_token(self):
        """Gets the thermal_token of this UserLicenseInfoUser.  # noqa: E501


        :return: The thermal_token of this UserLicenseInfoUser.  # noqa: E501
        :rtype: str
        """
        return self._thermal_token

    @thermal_token.setter
    def thermal_token(self, thermal_token):
        """Sets the thermal_token of this UserLicenseInfoUser.


        :param thermal_token: The thermal_token of this UserLicenseInfoUser.  # noqa: E501
        :type: str
        """

        self._thermal_token = thermal_token

    @property
    def groups(self):
        """Gets the groups of this UserLicenseInfoUser.  # noqa: E501


        :return: The groups of this UserLicenseInfoUser.  # noqa: E501
        :rtype: list[str]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this UserLicenseInfoUser.


        :param groups: The groups of this UserLicenseInfoUser.  # noqa: E501
        :type: list[str]
        """

        self._groups = groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserLicenseInfoUser):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserLicenseInfoUser):
            return True

        return self.to_dict() != other.to_dict()
