# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class UserLicenseInfoLicenses(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'feature': 'str',
        'description': 'str',
        'expiration': 'str',
        'group_limit': 'int'
    }

    attribute_map = {
        'feature': 'feature',
        'description': 'description',
        'expiration': 'expiration',
        'group_limit': 'group_limit'
    }

    def __init__(self, feature=None, description=None, expiration=None, group_limit=None, local_vars_configuration=None):  # noqa: E501
        """UserLicenseInfoLicenses - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._feature = None
        self._description = None
        self._expiration = None
        self._group_limit = None
        self.discriminator = None

        if feature is not None:
            self.feature = feature
        if description is not None:
            self.description = description
        if expiration is not None:
            self.expiration = expiration
        if group_limit is not None:
            self.group_limit = group_limit

    @property
    def feature(self):
        """Gets the feature of this UserLicenseInfoLicenses.  # noqa: E501


        :return: The feature of this UserLicenseInfoLicenses.  # noqa: E501
        :rtype: str
        """
        return self._feature

    @feature.setter
    def feature(self, feature):
        """Sets the feature of this UserLicenseInfoLicenses.


        :param feature: The feature of this UserLicenseInfoLicenses.  # noqa: E501
        :type: str
        """

        self._feature = feature

    @property
    def description(self):
        """Gets the description of this UserLicenseInfoLicenses.  # noqa: E501


        :return: The description of this UserLicenseInfoLicenses.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UserLicenseInfoLicenses.


        :param description: The description of this UserLicenseInfoLicenses.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def expiration(self):
        """Gets the expiration of this UserLicenseInfoLicenses.  # noqa: E501


        :return: The expiration of this UserLicenseInfoLicenses.  # noqa: E501
        :rtype: str
        """
        return self._expiration

    @expiration.setter
    def expiration(self, expiration):
        """Sets the expiration of this UserLicenseInfoLicenses.


        :param expiration: The expiration of this UserLicenseInfoLicenses.  # noqa: E501
        :type: str
        """

        self._expiration = expiration

    @property
    def group_limit(self):
        """Gets the group_limit of this UserLicenseInfoLicenses.  # noqa: E501


        :return: The group_limit of this UserLicenseInfoLicenses.  # noqa: E501
        :rtype: int
        """
        return self._group_limit

    @group_limit.setter
    def group_limit(self, group_limit):
        """Sets the group_limit of this UserLicenseInfoLicenses.


        :param group_limit: The group_limit of this UserLicenseInfoLicenses.  # noqa: E501
        :type: int
        """

        self._group_limit = group_limit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserLicenseInfoLicenses):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserLicenseInfoLicenses):
            return True

        return self.to_dict() != other.to_dict()
