# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class ViaArray(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'index': 'int',
        'type': 'str',
        'type_id': 'int',
        'leaf': 'bool',
        'parent': 'int',
        'visible': 'bool',
        'active': 'bool',
        'x': 'str',
        'y': 'str',
        'z': 'str',
        'dx': 'str',
        'dy': 'str',
        'dz': 'str',
        'x_calc': 'float',
        'y_calc': 'float',
        'z_calc': 'float',
        'dx_calc': 'float',
        'dy_calc': 'float',
        'dz_calc': 'float',
        'xcount': 'str',
        'ycount': 'str',
        'xpitch': 'str',
        'ypitch': 'str',
        'diameter': 'str',
        'xcount_calc': 'int',
        'ycount_calc': 'int',
        'xpitch_calc': 'float',
        'ypitch_calc': 'float',
        'diameter_calc': 'float',
        'material': 'int',
        'fill_material': 'int',
        'lumped': 'bool',
        'hc': 'str',
        'color': 'str',
        'fill_color': 'str',
        'material_name': 'str',
        'fill_material_name': 'str',
        'composite_material': 'list[float]',
        'is_plated': 'bool',
        'inner_diameter': 'str',
        'inner_diameter_calc': 'float',
        'hole_material': 'int',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'index': 'index',
        'type': 'type',
        'type_id': 'type_id',
        'leaf': 'leaf',
        'parent': 'parent',
        'visible': 'visible',
        'active': 'active',
        'x': 'x',
        'y': 'y',
        'z': 'z',
        'dx': 'dx',
        'dy': 'dy',
        'dz': 'dz',
        'x_calc': 'x_calc',
        'y_calc': 'y_calc',
        'z_calc': 'z_calc',
        'dx_calc': 'dx_calc',
        'dy_calc': 'dy_calc',
        'dz_calc': 'dz_calc',
        'xcount': 'xcount',
        'ycount': 'ycount',
        'xpitch': 'xpitch',
        'ypitch': 'ypitch',
        'diameter': 'diameter',
        'xcount_calc': 'xcount_calc',
        'ycount_calc': 'ycount_calc',
        'xpitch_calc': 'xpitch_calc',
        'ypitch_calc': 'ypitch_calc',
        'diameter_calc': 'diameter_calc',
        'material': 'material',
        'fill_material': 'fill_material',
        'lumped': 'lumped',
        'hc': 'hc',
        'color': 'color',
        'fill_color': 'fill_color',
        'material_name': 'material_name',
        'fill_material_name': 'fill_material_name',
        'composite_material': 'composite_material',
        'is_plated': 'is_plated',
        'inner_diameter': 'inner_diameter',
        'inner_diameter_calc': 'inner_diameter_calc',
        'hole_material': 'hole_material',
        'timestamp': 'timestamp'
    }

    def __init__(self, id=None, name=None, index=None, type=None, type_id=None, leaf=None, parent=None, visible=None, active=None, x=None, y=None, z=None, dx=None, dy=None, dz=None, x_calc=None, y_calc=None, z_calc=None, dx_calc=None, dy_calc=None, dz_calc=None, xcount=None, ycount=None, xpitch=None, ypitch=None, diameter=None, xcount_calc=None, ycount_calc=None, xpitch_calc=None, ypitch_calc=None, diameter_calc=None, material=None, fill_material=None, lumped=None, hc=None, color=None, fill_color=None, material_name=None, fill_material_name=None, composite_material=None, is_plated=None, inner_diameter=None, inner_diameter_calc=None, hole_material=None, timestamp=None, local_vars_configuration=None):  # noqa: E501
        """ViaArray - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._index = None
        self._type = None
        self._type_id = None
        self._leaf = None
        self._parent = None
        self._visible = None
        self._active = None
        self._x = None
        self._y = None
        self._z = None
        self._dx = None
        self._dy = None
        self._dz = None
        self._x_calc = None
        self._y_calc = None
        self._z_calc = None
        self._dx_calc = None
        self._dy_calc = None
        self._dz_calc = None
        self._xcount = None
        self._ycount = None
        self._xpitch = None
        self._ypitch = None
        self._diameter = None
        self._xcount_calc = None
        self._ycount_calc = None
        self._xpitch_calc = None
        self._ypitch_calc = None
        self._diameter_calc = None
        self._material = None
        self._fill_material = None
        self._lumped = None
        self._hc = None
        self._color = None
        self._fill_color = None
        self._material_name = None
        self._fill_material_name = None
        self._composite_material = None
        self._is_plated = None
        self._inner_diameter = None
        self._inner_diameter_calc = None
        self._hole_material = None
        self._timestamp = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.index = index
        if type is not None:
            self.type = type
        if type_id is not None:
            self.type_id = type_id
        if leaf is not None:
            self.leaf = leaf
        self.parent = parent
        if visible is not None:
            self.visible = visible
        if active is not None:
            self.active = active
        self.x = x
        self.y = y
        self.z = z
        self.dx = dx
        self.dy = dy
        self.dz = dz
        if x_calc is not None:
            self.x_calc = x_calc
        if y_calc is not None:
            self.y_calc = y_calc
        if z_calc is not None:
            self.z_calc = z_calc
        if dx_calc is not None:
            self.dx_calc = dx_calc
        if dy_calc is not None:
            self.dy_calc = dy_calc
        if dz_calc is not None:
            self.dz_calc = dz_calc
        self.xcount = xcount
        self.ycount = ycount
        self.xpitch = xpitch
        self.ypitch = ypitch
        self.diameter = diameter
        if xcount_calc is not None:
            self.xcount_calc = xcount_calc
        if ycount_calc is not None:
            self.ycount_calc = ycount_calc
        if xpitch_calc is not None:
            self.xpitch_calc = xpitch_calc
        if ypitch_calc is not None:
            self.ypitch_calc = ypitch_calc
        if diameter_calc is not None:
            self.diameter_calc = diameter_calc
        self.material = material
        self.fill_material = fill_material
        if lumped is not None:
            self.lumped = lumped
        self.hc = hc
        if color is not None:
            self.color = color
        self.fill_color = fill_color
        if material_name is not None:
            self.material_name = material_name
        self.fill_material_name = fill_material_name
        self.composite_material = composite_material
        if is_plated is not None:
            self.is_plated = is_plated
        if inner_diameter is not None:
            self.inner_diameter = inner_diameter
        if inner_diameter_calc is not None:
            self.inner_diameter_calc = inner_diameter_calc
        self.hole_material = hole_material
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def id(self):
        """Gets the id of this ViaArray.  # noqa: E501


        :return: The id of this ViaArray.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ViaArray.


        :param id: The id of this ViaArray.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ViaArray.  # noqa: E501


        :return: The name of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ViaArray.


        :param name: The name of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def index(self):
        """Gets the index of this ViaArray.  # noqa: E501


        :return: The index of this ViaArray.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this ViaArray.


        :param index: The index of this ViaArray.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and index is None:  # noqa: E501
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index is not None and index > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `index`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index is not None and index < 0):  # noqa: E501
            raise ValueError("Invalid value for `index`, must be a value greater than or equal to `0`")  # noqa: E501

        self._index = index

    @property
    def type(self):
        """Gets the type of this ViaArray.  # noqa: E501


        :return: The type of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ViaArray.


        :param type: The type of this ViaArray.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def type_id(self):
        """Gets the type_id of this ViaArray.  # noqa: E501


        :return: The type_id of this ViaArray.  # noqa: E501
        :rtype: int
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id):
        """Sets the type_id of this ViaArray.


        :param type_id: The type_id of this ViaArray.  # noqa: E501
        :type: int
        """

        self._type_id = type_id

    @property
    def leaf(self):
        """Gets the leaf of this ViaArray.  # noqa: E501


        :return: The leaf of this ViaArray.  # noqa: E501
        :rtype: bool
        """
        return self._leaf

    @leaf.setter
    def leaf(self, leaf):
        """Sets the leaf of this ViaArray.


        :param leaf: The leaf of this ViaArray.  # noqa: E501
        :type: bool
        """

        self._leaf = leaf

    @property
    def parent(self):
        """Gets the parent of this ViaArray.  # noqa: E501


        :return: The parent of this ViaArray.  # noqa: E501
        :rtype: int
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this ViaArray.


        :param parent: The parent of this ViaArray.  # noqa: E501
        :type: int
        """

        self._parent = parent

    @property
    def visible(self):
        """Gets the visible of this ViaArray.  # noqa: E501


        :return: The visible of this ViaArray.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this ViaArray.


        :param visible: The visible of this ViaArray.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    @property
    def active(self):
        """Gets the active of this ViaArray.  # noqa: E501


        :return: The active of this ViaArray.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this ViaArray.


        :param active: The active of this ViaArray.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def x(self):
        """Gets the x of this ViaArray.  # noqa: E501


        :return: The x of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this ViaArray.


        :param x: The x of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and x is None:  # noqa: E501
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                x is not None and len(x) < 1):
            raise ValueError("Invalid value for `x`, length must be greater than or equal to `1`")  # noqa: E501

        self._x = x

    @property
    def y(self):
        """Gets the y of this ViaArray.  # noqa: E501


        :return: The y of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this ViaArray.


        :param y: The y of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and y is None:  # noqa: E501
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                y is not None and len(y) < 1):
            raise ValueError("Invalid value for `y`, length must be greater than or equal to `1`")  # noqa: E501

        self._y = y

    @property
    def z(self):
        """Gets the z of this ViaArray.  # noqa: E501


        :return: The z of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._z

    @z.setter
    def z(self, z):
        """Sets the z of this ViaArray.


        :param z: The z of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and z is None:  # noqa: E501
            raise ValueError("Invalid value for `z`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                z is not None and len(z) < 1):
            raise ValueError("Invalid value for `z`, length must be greater than or equal to `1`")  # noqa: E501

        self._z = z

    @property
    def dx(self):
        """Gets the dx of this ViaArray.  # noqa: E501


        :return: The dx of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._dx

    @dx.setter
    def dx(self, dx):
        """Sets the dx of this ViaArray.


        :param dx: The dx of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and dx is None:  # noqa: E501
            raise ValueError("Invalid value for `dx`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                dx is not None and len(dx) < 1):
            raise ValueError("Invalid value for `dx`, length must be greater than or equal to `1`")  # noqa: E501

        self._dx = dx

    @property
    def dy(self):
        """Gets the dy of this ViaArray.  # noqa: E501


        :return: The dy of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._dy

    @dy.setter
    def dy(self, dy):
        """Sets the dy of this ViaArray.


        :param dy: The dy of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and dy is None:  # noqa: E501
            raise ValueError("Invalid value for `dy`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                dy is not None and len(dy) < 1):
            raise ValueError("Invalid value for `dy`, length must be greater than or equal to `1`")  # noqa: E501

        self._dy = dy

    @property
    def dz(self):
        """Gets the dz of this ViaArray.  # noqa: E501


        :return: The dz of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._dz

    @dz.setter
    def dz(self, dz):
        """Sets the dz of this ViaArray.


        :param dz: The dz of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and dz is None:  # noqa: E501
            raise ValueError("Invalid value for `dz`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                dz is not None and len(dz) < 1):
            raise ValueError("Invalid value for `dz`, length must be greater than or equal to `1`")  # noqa: E501

        self._dz = dz

    @property
    def x_calc(self):
        """Gets the x_calc of this ViaArray.  # noqa: E501


        :return: The x_calc of this ViaArray.  # noqa: E501
        :rtype: float
        """
        return self._x_calc

    @x_calc.setter
    def x_calc(self, x_calc):
        """Sets the x_calc of this ViaArray.


        :param x_calc: The x_calc of this ViaArray.  # noqa: E501
        :type: float
        """

        self._x_calc = x_calc

    @property
    def y_calc(self):
        """Gets the y_calc of this ViaArray.  # noqa: E501


        :return: The y_calc of this ViaArray.  # noqa: E501
        :rtype: float
        """
        return self._y_calc

    @y_calc.setter
    def y_calc(self, y_calc):
        """Sets the y_calc of this ViaArray.


        :param y_calc: The y_calc of this ViaArray.  # noqa: E501
        :type: float
        """

        self._y_calc = y_calc

    @property
    def z_calc(self):
        """Gets the z_calc of this ViaArray.  # noqa: E501


        :return: The z_calc of this ViaArray.  # noqa: E501
        :rtype: float
        """
        return self._z_calc

    @z_calc.setter
    def z_calc(self, z_calc):
        """Sets the z_calc of this ViaArray.


        :param z_calc: The z_calc of this ViaArray.  # noqa: E501
        :type: float
        """

        self._z_calc = z_calc

    @property
    def dx_calc(self):
        """Gets the dx_calc of this ViaArray.  # noqa: E501


        :return: The dx_calc of this ViaArray.  # noqa: E501
        :rtype: float
        """
        return self._dx_calc

    @dx_calc.setter
    def dx_calc(self, dx_calc):
        """Sets the dx_calc of this ViaArray.


        :param dx_calc: The dx_calc of this ViaArray.  # noqa: E501
        :type: float
        """

        self._dx_calc = dx_calc

    @property
    def dy_calc(self):
        """Gets the dy_calc of this ViaArray.  # noqa: E501


        :return: The dy_calc of this ViaArray.  # noqa: E501
        :rtype: float
        """
        return self._dy_calc

    @dy_calc.setter
    def dy_calc(self, dy_calc):
        """Sets the dy_calc of this ViaArray.


        :param dy_calc: The dy_calc of this ViaArray.  # noqa: E501
        :type: float
        """

        self._dy_calc = dy_calc

    @property
    def dz_calc(self):
        """Gets the dz_calc of this ViaArray.  # noqa: E501


        :return: The dz_calc of this ViaArray.  # noqa: E501
        :rtype: float
        """
        return self._dz_calc

    @dz_calc.setter
    def dz_calc(self, dz_calc):
        """Sets the dz_calc of this ViaArray.


        :param dz_calc: The dz_calc of this ViaArray.  # noqa: E501
        :type: float
        """

        self._dz_calc = dz_calc

    @property
    def xcount(self):
        """Gets the xcount of this ViaArray.  # noqa: E501


        :return: The xcount of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._xcount

    @xcount.setter
    def xcount(self, xcount):
        """Sets the xcount of this ViaArray.


        :param xcount: The xcount of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and xcount is None:  # noqa: E501
            raise ValueError("Invalid value for `xcount`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                xcount is not None and len(xcount) < 1):
            raise ValueError("Invalid value for `xcount`, length must be greater than or equal to `1`")  # noqa: E501

        self._xcount = xcount

    @property
    def ycount(self):
        """Gets the ycount of this ViaArray.  # noqa: E501


        :return: The ycount of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._ycount

    @ycount.setter
    def ycount(self, ycount):
        """Sets the ycount of this ViaArray.


        :param ycount: The ycount of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and ycount is None:  # noqa: E501
            raise ValueError("Invalid value for `ycount`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                ycount is not None and len(ycount) < 1):
            raise ValueError("Invalid value for `ycount`, length must be greater than or equal to `1`")  # noqa: E501

        self._ycount = ycount

    @property
    def xpitch(self):
        """Gets the xpitch of this ViaArray.  # noqa: E501


        :return: The xpitch of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._xpitch

    @xpitch.setter
    def xpitch(self, xpitch):
        """Sets the xpitch of this ViaArray.


        :param xpitch: The xpitch of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and xpitch is None:  # noqa: E501
            raise ValueError("Invalid value for `xpitch`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                xpitch is not None and len(xpitch) < 1):
            raise ValueError("Invalid value for `xpitch`, length must be greater than or equal to `1`")  # noqa: E501

        self._xpitch = xpitch

    @property
    def ypitch(self):
        """Gets the ypitch of this ViaArray.  # noqa: E501


        :return: The ypitch of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._ypitch

    @ypitch.setter
    def ypitch(self, ypitch):
        """Sets the ypitch of this ViaArray.


        :param ypitch: The ypitch of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and ypitch is None:  # noqa: E501
            raise ValueError("Invalid value for `ypitch`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                ypitch is not None and len(ypitch) < 1):
            raise ValueError("Invalid value for `ypitch`, length must be greater than or equal to `1`")  # noqa: E501

        self._ypitch = ypitch

    @property
    def diameter(self):
        """Gets the diameter of this ViaArray.  # noqa: E501


        :return: The diameter of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._diameter

    @diameter.setter
    def diameter(self, diameter):
        """Sets the diameter of this ViaArray.


        :param diameter: The diameter of this ViaArray.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and diameter is None:  # noqa: E501
            raise ValueError("Invalid value for `diameter`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                diameter is not None and len(diameter) < 1):
            raise ValueError("Invalid value for `diameter`, length must be greater than or equal to `1`")  # noqa: E501

        self._diameter = diameter

    @property
    def xcount_calc(self):
        """Gets the xcount_calc of this ViaArray.  # noqa: E501


        :return: The xcount_calc of this ViaArray.  # noqa: E501
        :rtype: int
        """
        return self._xcount_calc

    @xcount_calc.setter
    def xcount_calc(self, xcount_calc):
        """Sets the xcount_calc of this ViaArray.


        :param xcount_calc: The xcount_calc of this ViaArray.  # noqa: E501
        :type: int
        """

        self._xcount_calc = xcount_calc

    @property
    def ycount_calc(self):
        """Gets the ycount_calc of this ViaArray.  # noqa: E501


        :return: The ycount_calc of this ViaArray.  # noqa: E501
        :rtype: int
        """
        return self._ycount_calc

    @ycount_calc.setter
    def ycount_calc(self, ycount_calc):
        """Sets the ycount_calc of this ViaArray.


        :param ycount_calc: The ycount_calc of this ViaArray.  # noqa: E501
        :type: int
        """

        self._ycount_calc = ycount_calc

    @property
    def xpitch_calc(self):
        """Gets the xpitch_calc of this ViaArray.  # noqa: E501


        :return: The xpitch_calc of this ViaArray.  # noqa: E501
        :rtype: float
        """
        return self._xpitch_calc

    @xpitch_calc.setter
    def xpitch_calc(self, xpitch_calc):
        """Sets the xpitch_calc of this ViaArray.


        :param xpitch_calc: The xpitch_calc of this ViaArray.  # noqa: E501
        :type: float
        """

        self._xpitch_calc = xpitch_calc

    @property
    def ypitch_calc(self):
        """Gets the ypitch_calc of this ViaArray.  # noqa: E501


        :return: The ypitch_calc of this ViaArray.  # noqa: E501
        :rtype: float
        """
        return self._ypitch_calc

    @ypitch_calc.setter
    def ypitch_calc(self, ypitch_calc):
        """Sets the ypitch_calc of this ViaArray.


        :param ypitch_calc: The ypitch_calc of this ViaArray.  # noqa: E501
        :type: float
        """

        self._ypitch_calc = ypitch_calc

    @property
    def diameter_calc(self):
        """Gets the diameter_calc of this ViaArray.  # noqa: E501


        :return: The diameter_calc of this ViaArray.  # noqa: E501
        :rtype: float
        """
        return self._diameter_calc

    @diameter_calc.setter
    def diameter_calc(self, diameter_calc):
        """Sets the diameter_calc of this ViaArray.


        :param diameter_calc: The diameter_calc of this ViaArray.  # noqa: E501
        :type: float
        """

        self._diameter_calc = diameter_calc

    @property
    def material(self):
        """Gets the material of this ViaArray.  # noqa: E501


        :return: The material of this ViaArray.  # noqa: E501
        :rtype: int
        """
        return self._material

    @material.setter
    def material(self, material):
        """Sets the material of this ViaArray.


        :param material: The material of this ViaArray.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and material is None:  # noqa: E501
            raise ValueError("Invalid value for `material`, must not be `None`")  # noqa: E501

        self._material = material

    @property
    def fill_material(self):
        """Gets the fill_material of this ViaArray.  # noqa: E501


        :return: The fill_material of this ViaArray.  # noqa: E501
        :rtype: int
        """
        return self._fill_material

    @fill_material.setter
    def fill_material(self, fill_material):
        """Sets the fill_material of this ViaArray.


        :param fill_material: The fill_material of this ViaArray.  # noqa: E501
        :type: int
        """

        self._fill_material = fill_material

    @property
    def lumped(self):
        """Gets the lumped of this ViaArray.  # noqa: E501


        :return: The lumped of this ViaArray.  # noqa: E501
        :rtype: bool
        """
        return self._lumped

    @lumped.setter
    def lumped(self, lumped):
        """Sets the lumped of this ViaArray.


        :param lumped: The lumped of this ViaArray.  # noqa: E501
        :type: bool
        """

        self._lumped = lumped

    @property
    def hc(self):
        """Gets the hc of this ViaArray.  # noqa: E501


        :return: The hc of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._hc

    @hc.setter
    def hc(self, hc):
        """Sets the hc of this ViaArray.


        :param hc: The hc of this ViaArray.  # noqa: E501
        :type: str
        """

        self._hc = hc

    @property
    def color(self):
        """Gets the color of this ViaArray.  # noqa: E501


        :return: The color of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this ViaArray.


        :param color: The color of this ViaArray.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def fill_color(self):
        """Gets the fill_color of this ViaArray.  # noqa: E501


        :return: The fill_color of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._fill_color

    @fill_color.setter
    def fill_color(self, fill_color):
        """Sets the fill_color of this ViaArray.


        :param fill_color: The fill_color of this ViaArray.  # noqa: E501
        :type: str
        """

        self._fill_color = fill_color

    @property
    def material_name(self):
        """Gets the material_name of this ViaArray.  # noqa: E501


        :return: The material_name of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._material_name

    @material_name.setter
    def material_name(self, material_name):
        """Sets the material_name of this ViaArray.


        :param material_name: The material_name of this ViaArray.  # noqa: E501
        :type: str
        """

        self._material_name = material_name

    @property
    def fill_material_name(self):
        """Gets the fill_material_name of this ViaArray.  # noqa: E501


        :return: The fill_material_name of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._fill_material_name

    @fill_material_name.setter
    def fill_material_name(self, fill_material_name):
        """Sets the fill_material_name of this ViaArray.


        :param fill_material_name: The fill_material_name of this ViaArray.  # noqa: E501
        :type: str
        """

        self._fill_material_name = fill_material_name

    @property
    def composite_material(self):
        """Gets the composite_material of this ViaArray.  # noqa: E501


        :return: The composite_material of this ViaArray.  # noqa: E501
        :rtype: list[float]
        """
        return self._composite_material

    @composite_material.setter
    def composite_material(self, composite_material):
        """Sets the composite_material of this ViaArray.


        :param composite_material: The composite_material of this ViaArray.  # noqa: E501
        :type: list[float]
        """

        self._composite_material = composite_material

    @property
    def is_plated(self):
        """Gets the is_plated of this ViaArray.  # noqa: E501


        :return: The is_plated of this ViaArray.  # noqa: E501
        :rtype: bool
        """
        return self._is_plated

    @is_plated.setter
    def is_plated(self, is_plated):
        """Sets the is_plated of this ViaArray.


        :param is_plated: The is_plated of this ViaArray.  # noqa: E501
        :type: bool
        """

        self._is_plated = is_plated

    @property
    def inner_diameter(self):
        """Gets the inner_diameter of this ViaArray.  # noqa: E501


        :return: The inner_diameter of this ViaArray.  # noqa: E501
        :rtype: str
        """
        return self._inner_diameter

    @inner_diameter.setter
    def inner_diameter(self, inner_diameter):
        """Sets the inner_diameter of this ViaArray.


        :param inner_diameter: The inner_diameter of this ViaArray.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                inner_diameter is not None and len(inner_diameter) < 1):
            raise ValueError("Invalid value for `inner_diameter`, length must be greater than or equal to `1`")  # noqa: E501

        self._inner_diameter = inner_diameter

    @property
    def inner_diameter_calc(self):
        """Gets the inner_diameter_calc of this ViaArray.  # noqa: E501


        :return: The inner_diameter_calc of this ViaArray.  # noqa: E501
        :rtype: float
        """
        return self._inner_diameter_calc

    @inner_diameter_calc.setter
    def inner_diameter_calc(self, inner_diameter_calc):
        """Sets the inner_diameter_calc of this ViaArray.


        :param inner_diameter_calc: The inner_diameter_calc of this ViaArray.  # noqa: E501
        :type: float
        """

        self._inner_diameter_calc = inner_diameter_calc

    @property
    def hole_material(self):
        """Gets the hole_material of this ViaArray.  # noqa: E501


        :return: The hole_material of this ViaArray.  # noqa: E501
        :rtype: int
        """
        return self._hole_material

    @hole_material.setter
    def hole_material(self, hole_material):
        """Sets the hole_material of this ViaArray.


        :param hole_material: The hole_material of this ViaArray.  # noqa: E501
        :type: int
        """

        self._hole_material = hole_material

    @property
    def timestamp(self):
        """Gets the timestamp of this ViaArray.  # noqa: E501


        :return: The timestamp of this ViaArray.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ViaArray.


        :param timestamp: The timestamp of this ViaArray.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ViaArray):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ViaArray):
            return True

        return self.to_dict() != other.to_dict()
