# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from danka_thermal_api.configuration import Configuration


class World(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ambient': 'float',
        'resolution': 'float',
        'precision': 'float',
        'iterations': 'int',
        'lumped': 'bool',
        'lump_limit': 'int',
        'hc': 'float',
        'abs_tol': 'float',
        'duration': 'float',
        'absolute': 'bool',
        'dxmin': 'str',
        'dxmax': 'str',
        'dymin': 'str',
        'dymax': 'str',
        'dzmin': 'str',
        'dzmax': 'str',
        'show_grid': 'bool',
        'show_outline': 'bool',
        'steps': 'int',
        'save_internal_temp': 'bool'
    }

    attribute_map = {
        'ambient': 'ambient',
        'resolution': 'resolution',
        'precision': 'precision',
        'iterations': 'iterations',
        'lumped': 'lumped',
        'lump_limit': 'lump_limit',
        'hc': 'hc',
        'abs_tol': 'abs_tol',
        'duration': 'duration',
        'absolute': 'absolute',
        'dxmin': 'dxmin',
        'dxmax': 'dxmax',
        'dymin': 'dymin',
        'dymax': 'dymax',
        'dzmin': 'dzmin',
        'dzmax': 'dzmax',
        'show_grid': 'show_grid',
        'show_outline': 'show_outline',
        'steps': 'steps',
        'save_internal_temp': 'save_internal_temp'
    }

    def __init__(self, ambient=None, resolution=None, precision=None, iterations=None, lumped=None, lump_limit=None, hc=None, abs_tol=None, duration=None, absolute=None, dxmin=None, dxmax=None, dymin=None, dymax=None, dzmin=None, dzmax=None, show_grid=None, show_outline=None, steps=None, save_internal_temp=None, local_vars_configuration=None):  # noqa: E501
        """World - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ambient = None
        self._resolution = None
        self._precision = None
        self._iterations = None
        self._lumped = None
        self._lump_limit = None
        self._hc = None
        self._abs_tol = None
        self._duration = None
        self._absolute = None
        self._dxmin = None
        self._dxmax = None
        self._dymin = None
        self._dymax = None
        self._dzmin = None
        self._dzmax = None
        self._show_grid = None
        self._show_outline = None
        self._steps = None
        self._save_internal_temp = None
        self.discriminator = None

        if ambient is not None:
            self.ambient = ambient
        if resolution is not None:
            self.resolution = resolution
        if precision is not None:
            self.precision = precision
        if iterations is not None:
            self.iterations = iterations
        if lumped is not None:
            self.lumped = lumped
        if lump_limit is not None:
            self.lump_limit = lump_limit
        if hc is not None:
            self.hc = hc
        if abs_tol is not None:
            self.abs_tol = abs_tol
        if duration is not None:
            self.duration = duration
        if absolute is not None:
            self.absolute = absolute
        if dxmin is not None:
            self.dxmin = dxmin
        if dxmax is not None:
            self.dxmax = dxmax
        if dymin is not None:
            self.dymin = dymin
        if dymax is not None:
            self.dymax = dymax
        if dzmin is not None:
            self.dzmin = dzmin
        if dzmax is not None:
            self.dzmax = dzmax
        if show_grid is not None:
            self.show_grid = show_grid
        if show_outline is not None:
            self.show_outline = show_outline
        if steps is not None:
            self.steps = steps
        if save_internal_temp is not None:
            self.save_internal_temp = save_internal_temp

    @property
    def ambient(self):
        """Gets the ambient of this World.  # noqa: E501


        :return: The ambient of this World.  # noqa: E501
        :rtype: float
        """
        return self._ambient

    @ambient.setter
    def ambient(self, ambient):
        """Sets the ambient of this World.


        :param ambient: The ambient of this World.  # noqa: E501
        :type: float
        """

        self._ambient = ambient

    @property
    def resolution(self):
        """Gets the resolution of this World.  # noqa: E501


        :return: The resolution of this World.  # noqa: E501
        :rtype: float
        """
        return self._resolution

    @resolution.setter
    def resolution(self, resolution):
        """Sets the resolution of this World.


        :param resolution: The resolution of this World.  # noqa: E501
        :type: float
        """

        self._resolution = resolution

    @property
    def precision(self):
        """Gets the precision of this World.  # noqa: E501


        :return: The precision of this World.  # noqa: E501
        :rtype: float
        """
        return self._precision

    @precision.setter
    def precision(self, precision):
        """Sets the precision of this World.


        :param precision: The precision of this World.  # noqa: E501
        :type: float
        """

        self._precision = precision

    @property
    def iterations(self):
        """Gets the iterations of this World.  # noqa: E501


        :return: The iterations of this World.  # noqa: E501
        :rtype: int
        """
        return self._iterations

    @iterations.setter
    def iterations(self, iterations):
        """Sets the iterations of this World.


        :param iterations: The iterations of this World.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                iterations is not None and iterations > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `iterations`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                iterations is not None and iterations < 0):  # noqa: E501
            raise ValueError("Invalid value for `iterations`, must be a value greater than or equal to `0`")  # noqa: E501

        self._iterations = iterations

    @property
    def lumped(self):
        """Gets the lumped of this World.  # noqa: E501


        :return: The lumped of this World.  # noqa: E501
        :rtype: bool
        """
        return self._lumped

    @lumped.setter
    def lumped(self, lumped):
        """Sets the lumped of this World.


        :param lumped: The lumped of this World.  # noqa: E501
        :type: bool
        """

        self._lumped = lumped

    @property
    def lump_limit(self):
        """Gets the lump_limit of this World.  # noqa: E501


        :return: The lump_limit of this World.  # noqa: E501
        :rtype: int
        """
        return self._lump_limit

    @lump_limit.setter
    def lump_limit(self, lump_limit):
        """Sets the lump_limit of this World.


        :param lump_limit: The lump_limit of this World.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                lump_limit is not None and lump_limit > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `lump_limit`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                lump_limit is not None and lump_limit < 0):  # noqa: E501
            raise ValueError("Invalid value for `lump_limit`, must be a value greater than or equal to `0`")  # noqa: E501

        self._lump_limit = lump_limit

    @property
    def hc(self):
        """Gets the hc of this World.  # noqa: E501


        :return: The hc of this World.  # noqa: E501
        :rtype: float
        """
        return self._hc

    @hc.setter
    def hc(self, hc):
        """Sets the hc of this World.


        :param hc: The hc of this World.  # noqa: E501
        :type: float
        """

        self._hc = hc

    @property
    def abs_tol(self):
        """Gets the abs_tol of this World.  # noqa: E501


        :return: The abs_tol of this World.  # noqa: E501
        :rtype: float
        """
        return self._abs_tol

    @abs_tol.setter
    def abs_tol(self, abs_tol):
        """Sets the abs_tol of this World.


        :param abs_tol: The abs_tol of this World.  # noqa: E501
        :type: float
        """

        self._abs_tol = abs_tol

    @property
    def duration(self):
        """Gets the duration of this World.  # noqa: E501


        :return: The duration of this World.  # noqa: E501
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this World.


        :param duration: The duration of this World.  # noqa: E501
        :type: float
        """

        self._duration = duration

    @property
    def absolute(self):
        """Gets the absolute of this World.  # noqa: E501


        :return: The absolute of this World.  # noqa: E501
        :rtype: bool
        """
        return self._absolute

    @absolute.setter
    def absolute(self, absolute):
        """Sets the absolute of this World.


        :param absolute: The absolute of this World.  # noqa: E501
        :type: bool
        """

        self._absolute = absolute

    @property
    def dxmin(self):
        """Gets the dxmin of this World.  # noqa: E501


        :return: The dxmin of this World.  # noqa: E501
        :rtype: str
        """
        return self._dxmin

    @dxmin.setter
    def dxmin(self, dxmin):
        """Sets the dxmin of this World.


        :param dxmin: The dxmin of this World.  # noqa: E501
        :type: str
        """

        self._dxmin = dxmin

    @property
    def dxmax(self):
        """Gets the dxmax of this World.  # noqa: E501


        :return: The dxmax of this World.  # noqa: E501
        :rtype: str
        """
        return self._dxmax

    @dxmax.setter
    def dxmax(self, dxmax):
        """Sets the dxmax of this World.


        :param dxmax: The dxmax of this World.  # noqa: E501
        :type: str
        """

        self._dxmax = dxmax

    @property
    def dymin(self):
        """Gets the dymin of this World.  # noqa: E501


        :return: The dymin of this World.  # noqa: E501
        :rtype: str
        """
        return self._dymin

    @dymin.setter
    def dymin(self, dymin):
        """Sets the dymin of this World.


        :param dymin: The dymin of this World.  # noqa: E501
        :type: str
        """

        self._dymin = dymin

    @property
    def dymax(self):
        """Gets the dymax of this World.  # noqa: E501


        :return: The dymax of this World.  # noqa: E501
        :rtype: str
        """
        return self._dymax

    @dymax.setter
    def dymax(self, dymax):
        """Sets the dymax of this World.


        :param dymax: The dymax of this World.  # noqa: E501
        :type: str
        """

        self._dymax = dymax

    @property
    def dzmin(self):
        """Gets the dzmin of this World.  # noqa: E501


        :return: The dzmin of this World.  # noqa: E501
        :rtype: str
        """
        return self._dzmin

    @dzmin.setter
    def dzmin(self, dzmin):
        """Sets the dzmin of this World.


        :param dzmin: The dzmin of this World.  # noqa: E501
        :type: str
        """

        self._dzmin = dzmin

    @property
    def dzmax(self):
        """Gets the dzmax of this World.  # noqa: E501


        :return: The dzmax of this World.  # noqa: E501
        :rtype: str
        """
        return self._dzmax

    @dzmax.setter
    def dzmax(self, dzmax):
        """Sets the dzmax of this World.


        :param dzmax: The dzmax of this World.  # noqa: E501
        :type: str
        """

        self._dzmax = dzmax

    @property
    def show_grid(self):
        """Gets the show_grid of this World.  # noqa: E501


        :return: The show_grid of this World.  # noqa: E501
        :rtype: bool
        """
        return self._show_grid

    @show_grid.setter
    def show_grid(self, show_grid):
        """Sets the show_grid of this World.


        :param show_grid: The show_grid of this World.  # noqa: E501
        :type: bool
        """

        self._show_grid = show_grid

    @property
    def show_outline(self):
        """Gets the show_outline of this World.  # noqa: E501


        :return: The show_outline of this World.  # noqa: E501
        :rtype: bool
        """
        return self._show_outline

    @show_outline.setter
    def show_outline(self, show_outline):
        """Sets the show_outline of this World.


        :param show_outline: The show_outline of this World.  # noqa: E501
        :type: bool
        """

        self._show_outline = show_outline

    @property
    def steps(self):
        """Gets the steps of this World.  # noqa: E501


        :return: The steps of this World.  # noqa: E501
        :rtype: int
        """
        return self._steps

    @steps.setter
    def steps(self, steps):
        """Sets the steps of this World.


        :param steps: The steps of this World.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                steps is not None and steps > 1000):  # noqa: E501
            raise ValueError("Invalid value for `steps`, must be a value less than or equal to `1000`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                steps is not None and steps < 1):  # noqa: E501
            raise ValueError("Invalid value for `steps`, must be a value greater than or equal to `1`")  # noqa: E501

        self._steps = steps

    @property
    def save_internal_temp(self):
        """Gets the save_internal_temp of this World.  # noqa: E501


        :return: The save_internal_temp of this World.  # noqa: E501
        :rtype: bool
        """
        return self._save_internal_temp

    @save_internal_temp.setter
    def save_internal_temp(self, save_internal_temp):
        """Sets the save_internal_temp of this World.


        :param save_internal_temp: The save_internal_temp of this World.  # noqa: E501
        :type: bool
        """

        self._save_internal_temp = save_internal_temp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, World):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, World):
            return True

        return self.to_dict() != other.to_dict()
